// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: proto/communication_player.proto

#ifndef PROTOBUF_INCLUDED_proto_2fcommunication_5fplayer_2eproto
#define PROTOBUF_INCLUDED_proto_2fcommunication_5fplayer_2eproto

#include <limits>
#include <string>

#include <google/protobuf/port_def.inc>
#if PROTOBUF_VERSION < 3007000
#error This file was generated by a newer version of protoc which is
#error incompatible with your Protocol Buffer headers. Please update
#error your headers.
#endif
#if 3007000 < PROTOBUF_MIN_PROTOC_VERSION
#error This file was generated by an older version of protoc which is
#error incompatible with your Protocol Buffer headers. Please
#error regenerate this file with a newer version of protoc.
#endif

#include <google/protobuf/port_undef.inc>
#include <google/protobuf/io/coded_stream.h>
#include <google/protobuf/arena.h>
#include <google/protobuf/arenastring.h>
#include <google/protobuf/generated_message_table_driven.h>
#include <google/protobuf/generated_message_util.h>
#include <google/protobuf/inlined_string_field.h>
#include <google/protobuf/metadata.h>
#include <google/protobuf/message.h>
#include <google/protobuf/repeated_field.h>  // IWYU pragma: export
#include <google/protobuf/extension_set.h>  // IWYU pragma: export
#include <google/protobuf/generated_enum_reflection.h>
#include <google/protobuf/unknown_field_set.h>
// @@protoc_insertion_point(includes)
#include <google/protobuf/port_def.inc>
#define PROTOBUF_INTERNAL_EXPORT_proto_2fcommunication_5fplayer_2eproto

// Internal implementation detail -- do not use these members.
struct TableStruct_proto_2fcommunication_5fplayer_2eproto {
  static const ::google::protobuf::internal::ParseTableField entries[]
    PROTOBUF_SECTION_VARIABLE(protodesc_cold);
  static const ::google::protobuf::internal::AuxillaryParseTableField aux[]
    PROTOBUF_SECTION_VARIABLE(protodesc_cold);
  static const ::google::protobuf::internal::ParseTable schema[10]
    PROTOBUF_SECTION_VARIABLE(protodesc_cold);
  static const ::google::protobuf::internal::FieldMetadata field_metadata[];
  static const ::google::protobuf::internal::SerializationTable serialization_table[];
  static const ::google::protobuf::uint32 offsets[];
};
void AddDescriptors_proto_2fcommunication_5fplayer_2eproto();
namespace comm_player {
class Command;
class CommandDefaultTypeInternal;
extern CommandDefaultTypeInternal _Command_default_instance_;
class Item;
class ItemDefaultTypeInternal;
extern ItemDefaultTypeInternal _Item_default_instance_;
class OtherInfo;
class OtherInfoDefaultTypeInternal;
extern OtherInfoDefaultTypeInternal _OtherInfo_default_instance_;
class Parachute;
class ParachuteDefaultTypeInternal;
extern ParachuteDefaultTypeInternal _Parachute_default_instance_;
class PlayerInfo;
class PlayerInfoDefaultTypeInternal;
extern PlayerInfoDefaultTypeInternal _PlayerInfo_default_instance_;
class PolarPosition;
class PolarPositionDefaultTypeInternal;
extern PolarPositionDefaultTypeInternal _PolarPosition_default_instance_;
class Route;
class RouteDefaultTypeInternal;
extern RouteDefaultTypeInternal _Route_default_instance_;
class SelfInfo;
class SelfInfoDefaultTypeInternal;
extern SelfInfoDefaultTypeInternal _SelfInfo_default_instance_;
class Sound;
class SoundDefaultTypeInternal;
extern SoundDefaultTypeInternal _Sound_default_instance_;
class XYPosition;
class XYPositionDefaultTypeInternal;
extern XYPositionDefaultTypeInternal _XYPosition_default_instance_;
}  // namespace comm_player
namespace google {
namespace protobuf {
template<> ::comm_player::Command* Arena::CreateMaybeMessage<::comm_player::Command>(Arena*);
template<> ::comm_player::Item* Arena::CreateMaybeMessage<::comm_player::Item>(Arena*);
template<> ::comm_player::OtherInfo* Arena::CreateMaybeMessage<::comm_player::OtherInfo>(Arena*);
template<> ::comm_player::Parachute* Arena::CreateMaybeMessage<::comm_player::Parachute>(Arena*);
template<> ::comm_player::PlayerInfo* Arena::CreateMaybeMessage<::comm_player::PlayerInfo>(Arena*);
template<> ::comm_player::PolarPosition* Arena::CreateMaybeMessage<::comm_player::PolarPosition>(Arena*);
template<> ::comm_player::Route* Arena::CreateMaybeMessage<::comm_player::Route>(Arena*);
template<> ::comm_player::SelfInfo* Arena::CreateMaybeMessage<::comm_player::SelfInfo>(Arena*);
template<> ::comm_player::Sound* Arena::CreateMaybeMessage<::comm_player::Sound>(Arena*);
template<> ::comm_player::XYPosition* Arena::CreateMaybeMessage<::comm_player::XYPosition>(Arena*);
}  // namespace protobuf
}  // namespace google
namespace comm_player {

enum CommandType {
  MOVE = 0,
  SHOOT = 1,
  PICKUP = 2,
  RADIO = 3,
  CommandType_INT_MIN_SENTINEL_DO_NOT_USE_ = std::numeric_limits<::google::protobuf::int32>::min(),
  CommandType_INT_MAX_SENTINEL_DO_NOT_USE_ = std::numeric_limits<::google::protobuf::int32>::max()
};
bool CommandType_IsValid(int value);
const CommandType CommandType_MIN = MOVE;
const CommandType CommandType_MAX = RADIO;
const int CommandType_ARRAYSIZE = CommandType_MAX + 1;

const ::google::protobuf::EnumDescriptor* CommandType_descriptor();
inline const ::std::string& CommandType_Name(CommandType value) {
  return ::google::protobuf::internal::NameOfEnum(
    CommandType_descriptor(), value);
}
inline bool CommandType_Parse(
    const ::std::string& name, CommandType* value) {
  return ::google::protobuf::internal::ParseNamedEnum<CommandType>(
    CommandType_descriptor(), name, value);
}
// ===================================================================

class PolarPosition final :
    public ::google::protobuf::Message /* @@protoc_insertion_point(class_definition:comm_player.PolarPosition) */ {
 public:
  PolarPosition();
  virtual ~PolarPosition();

  PolarPosition(const PolarPosition& from);

  inline PolarPosition& operator=(const PolarPosition& from) {
    CopyFrom(from);
    return *this;
  }
  #if LANG_CXX11
  PolarPosition(PolarPosition&& from) noexcept
    : PolarPosition() {
    *this = ::std::move(from);
  }

  inline PolarPosition& operator=(PolarPosition&& from) noexcept {
    if (GetArenaNoVirtual() == from.GetArenaNoVirtual()) {
      if (this != &from) InternalSwap(&from);
    } else {
      CopyFrom(from);
    }
    return *this;
  }
  #endif
  static const ::google::protobuf::Descriptor* descriptor() {
    return default_instance().GetDescriptor();
  }
  static const PolarPosition& default_instance();

  static void InitAsDefaultInstance();  // FOR INTERNAL USE ONLY
  static inline const PolarPosition* internal_default_instance() {
    return reinterpret_cast<const PolarPosition*>(
               &_PolarPosition_default_instance_);
  }
  static constexpr int kIndexInFileMessages =
    0;

  void Swap(PolarPosition* other);
  friend void swap(PolarPosition& a, PolarPosition& b) {
    a.Swap(&b);
  }

  // implements Message ----------------------------------------------

  inline PolarPosition* New() const final {
    return CreateMaybeMessage<PolarPosition>(nullptr);
  }

  PolarPosition* New(::google::protobuf::Arena* arena) const final {
    return CreateMaybeMessage<PolarPosition>(arena);
  }
  void CopyFrom(const ::google::protobuf::Message& from) final;
  void MergeFrom(const ::google::protobuf::Message& from) final;
  void CopyFrom(const PolarPosition& from);
  void MergeFrom(const PolarPosition& from);
  PROTOBUF_ATTRIBUTE_REINITIALIZES void Clear() final;
  bool IsInitialized() const final;

  size_t ByteSizeLong() const final;
  #if GOOGLE_PROTOBUF_ENABLE_EXPERIMENTAL_PARSER
  static const char* _InternalParse(const char* begin, const char* end, void* object, ::google::protobuf::internal::ParseContext* ctx);
  ::google::protobuf::internal::ParseFunc _ParseFunc() const final { return _InternalParse; }
  #else
  bool MergePartialFromCodedStream(
      ::google::protobuf::io::CodedInputStream* input) final;
  #endif  // GOOGLE_PROTOBUF_ENABLE_EXPERIMENTAL_PARSER
  void SerializeWithCachedSizes(
      ::google::protobuf::io::CodedOutputStream* output) const final;
  ::google::protobuf::uint8* InternalSerializeWithCachedSizesToArray(
      ::google::protobuf::uint8* target) const final;
  int GetCachedSize() const final { return _cached_size_.Get(); }

  private:
  void SharedCtor();
  void SharedDtor();
  void SetCachedSize(int size) const final;
  void InternalSwap(PolarPosition* other);
  private:
  inline ::google::protobuf::Arena* GetArenaNoVirtual() const {
    return nullptr;
  }
  inline void* MaybeArenaPtr() const {
    return nullptr;
  }
  public:

  ::google::protobuf::Metadata GetMetadata() const final;

  // nested types ----------------------------------------------------

  // accessors -------------------------------------------------------

  // double distance = 1;
  void clear_distance();
  static const int kDistanceFieldNumber = 1;
  double distance() const;
  void set_distance(double value);

  // double angle = 2;
  void clear_angle();
  static const int kAngleFieldNumber = 2;
  double angle() const;
  void set_angle(double value);

  // @@protoc_insertion_point(class_scope:comm_player.PolarPosition)
 private:
  class HasBitSetters;

  ::google::protobuf::internal::InternalMetadataWithArena _internal_metadata_;
  double distance_;
  double angle_;
  mutable ::google::protobuf::internal::CachedSize _cached_size_;
  friend struct ::TableStruct_proto_2fcommunication_5fplayer_2eproto;
};
// -------------------------------------------------------------------

class XYPosition final :
    public ::google::protobuf::Message /* @@protoc_insertion_point(class_definition:comm_player.XYPosition) */ {
 public:
  XYPosition();
  virtual ~XYPosition();

  XYPosition(const XYPosition& from);

  inline XYPosition& operator=(const XYPosition& from) {
    CopyFrom(from);
    return *this;
  }
  #if LANG_CXX11
  XYPosition(XYPosition&& from) noexcept
    : XYPosition() {
    *this = ::std::move(from);
  }

  inline XYPosition& operator=(XYPosition&& from) noexcept {
    if (GetArenaNoVirtual() == from.GetArenaNoVirtual()) {
      if (this != &from) InternalSwap(&from);
    } else {
      CopyFrom(from);
    }
    return *this;
  }
  #endif
  static const ::google::protobuf::Descriptor* descriptor() {
    return default_instance().GetDescriptor();
  }
  static const XYPosition& default_instance();

  static void InitAsDefaultInstance();  // FOR INTERNAL USE ONLY
  static inline const XYPosition* internal_default_instance() {
    return reinterpret_cast<const XYPosition*>(
               &_XYPosition_default_instance_);
  }
  static constexpr int kIndexInFileMessages =
    1;

  void Swap(XYPosition* other);
  friend void swap(XYPosition& a, XYPosition& b) {
    a.Swap(&b);
  }

  // implements Message ----------------------------------------------

  inline XYPosition* New() const final {
    return CreateMaybeMessage<XYPosition>(nullptr);
  }

  XYPosition* New(::google::protobuf::Arena* arena) const final {
    return CreateMaybeMessage<XYPosition>(arena);
  }
  void CopyFrom(const ::google::protobuf::Message& from) final;
  void MergeFrom(const ::google::protobuf::Message& from) final;
  void CopyFrom(const XYPosition& from);
  void MergeFrom(const XYPosition& from);
  PROTOBUF_ATTRIBUTE_REINITIALIZES void Clear() final;
  bool IsInitialized() const final;

  size_t ByteSizeLong() const final;
  #if GOOGLE_PROTOBUF_ENABLE_EXPERIMENTAL_PARSER
  static const char* _InternalParse(const char* begin, const char* end, void* object, ::google::protobuf::internal::ParseContext* ctx);
  ::google::protobuf::internal::ParseFunc _ParseFunc() const final { return _InternalParse; }
  #else
  bool MergePartialFromCodedStream(
      ::google::protobuf::io::CodedInputStream* input) final;
  #endif  // GOOGLE_PROTOBUF_ENABLE_EXPERIMENTAL_PARSER
  void SerializeWithCachedSizes(
      ::google::protobuf::io::CodedOutputStream* output) const final;
  ::google::protobuf::uint8* InternalSerializeWithCachedSizesToArray(
      ::google::protobuf::uint8* target) const final;
  int GetCachedSize() const final { return _cached_size_.Get(); }

  private:
  void SharedCtor();
  void SharedDtor();
  void SetCachedSize(int size) const final;
  void InternalSwap(XYPosition* other);
  private:
  inline ::google::protobuf::Arena* GetArenaNoVirtual() const {
    return nullptr;
  }
  inline void* MaybeArenaPtr() const {
    return nullptr;
  }
  public:

  ::google::protobuf::Metadata GetMetadata() const final;

  // nested types ----------------------------------------------------

  // accessors -------------------------------------------------------

  // double x = 1;
  void clear_x();
  static const int kXFieldNumber = 1;
  double x() const;
  void set_x(double value);

  // double y = 2;
  void clear_y();
  static const int kYFieldNumber = 2;
  double y() const;
  void set_y(double value);

  // @@protoc_insertion_point(class_scope:comm_player.XYPosition)
 private:
  class HasBitSetters;

  ::google::protobuf::internal::InternalMetadataWithArena _internal_metadata_;
  double x_;
  double y_;
  mutable ::google::protobuf::internal::CachedSize _cached_size_;
  friend struct ::TableStruct_proto_2fcommunication_5fplayer_2eproto;
};
// -------------------------------------------------------------------

class Item final :
    public ::google::protobuf::Message /* @@protoc_insertion_point(class_definition:comm_player.Item) */ {
 public:
  Item();
  virtual ~Item();

  Item(const Item& from);

  inline Item& operator=(const Item& from) {
    CopyFrom(from);
    return *this;
  }
  #if LANG_CXX11
  Item(Item&& from) noexcept
    : Item() {
    *this = ::std::move(from);
  }

  inline Item& operator=(Item&& from) noexcept {
    if (GetArenaNoVirtual() == from.GetArenaNoVirtual()) {
      if (this != &from) InternalSwap(&from);
    } else {
      CopyFrom(from);
    }
    return *this;
  }
  #endif
  static const ::google::protobuf::Descriptor* descriptor() {
    return default_instance().GetDescriptor();
  }
  static const Item& default_instance();

  static void InitAsDefaultInstance();  // FOR INTERNAL USE ONLY
  static inline const Item* internal_default_instance() {
    return reinterpret_cast<const Item*>(
               &_Item_default_instance_);
  }
  static constexpr int kIndexInFileMessages =
    2;

  void Swap(Item* other);
  friend void swap(Item& a, Item& b) {
    a.Swap(&b);
  }

  // implements Message ----------------------------------------------

  inline Item* New() const final {
    return CreateMaybeMessage<Item>(nullptr);
  }

  Item* New(::google::protobuf::Arena* arena) const final {
    return CreateMaybeMessage<Item>(arena);
  }
  void CopyFrom(const ::google::protobuf::Message& from) final;
  void MergeFrom(const ::google::protobuf::Message& from) final;
  void CopyFrom(const Item& from);
  void MergeFrom(const Item& from);
  PROTOBUF_ATTRIBUTE_REINITIALIZES void Clear() final;
  bool IsInitialized() const final;

  size_t ByteSizeLong() const final;
  #if GOOGLE_PROTOBUF_ENABLE_EXPERIMENTAL_PARSER
  static const char* _InternalParse(const char* begin, const char* end, void* object, ::google::protobuf::internal::ParseContext* ctx);
  ::google::protobuf::internal::ParseFunc _ParseFunc() const final { return _InternalParse; }
  #else
  bool MergePartialFromCodedStream(
      ::google::protobuf::io::CodedInputStream* input) final;
  #endif  // GOOGLE_PROTOBUF_ENABLE_EXPERIMENTAL_PARSER
  void SerializeWithCachedSizes(
      ::google::protobuf::io::CodedOutputStream* output) const final;
  ::google::protobuf::uint8* InternalSerializeWithCachedSizesToArray(
      ::google::protobuf::uint8* target) const final;
  int GetCachedSize() const final { return _cached_size_.Get(); }

  private:
  void SharedCtor();
  void SharedDtor();
  void SetCachedSize(int size) const final;
  void InternalSwap(Item* other);
  private:
  inline ::google::protobuf::Arena* GetArenaNoVirtual() const {
    return nullptr;
  }
  inline void* MaybeArenaPtr() const {
    return nullptr;
  }
  public:

  ::google::protobuf::Metadata GetMetadata() const final;

  // nested types ----------------------------------------------------

  // accessors -------------------------------------------------------

  // .comm_player.PolarPosition pos = 3;
  bool has_pos() const;
  void clear_pos();
  static const int kPosFieldNumber = 3;
  const ::comm_player::PolarPosition& pos() const;
  ::comm_player::PolarPosition* release_pos();
  ::comm_player::PolarPosition* mutable_pos();
  void set_allocated_pos(::comm_player::PolarPosition* pos);

  // int32 item_ID = 1;
  void clear_item_id();
  static const int kItemIDFieldNumber = 1;
  ::google::protobuf::int32 item_id() const;
  void set_item_id(::google::protobuf::int32 value);

  // int32 type = 2;
  void clear_type();
  static const int kTypeFieldNumber = 2;
  ::google::protobuf::int32 type() const;
  void set_type(::google::protobuf::int32 value);

  // int32 durability = 4;
  void clear_durability();
  static const int kDurabilityFieldNumber = 4;
  ::google::protobuf::int32 durability() const;
  void set_durability(::google::protobuf::int32 value);

  // @@protoc_insertion_point(class_scope:comm_player.Item)
 private:
  class HasBitSetters;

  ::google::protobuf::internal::InternalMetadataWithArena _internal_metadata_;
  ::comm_player::PolarPosition* pos_;
  ::google::protobuf::int32 item_id_;
  ::google::protobuf::int32 type_;
  ::google::protobuf::int32 durability_;
  mutable ::google::protobuf::internal::CachedSize _cached_size_;
  friend struct ::TableStruct_proto_2fcommunication_5fplayer_2eproto;
};
// -------------------------------------------------------------------

class SelfInfo final :
    public ::google::protobuf::Message /* @@protoc_insertion_point(class_definition:comm_player.SelfInfo) */ {
 public:
  SelfInfo();
  virtual ~SelfInfo();

  SelfInfo(const SelfInfo& from);

  inline SelfInfo& operator=(const SelfInfo& from) {
    CopyFrom(from);
    return *this;
  }
  #if LANG_CXX11
  SelfInfo(SelfInfo&& from) noexcept
    : SelfInfo() {
    *this = ::std::move(from);
  }

  inline SelfInfo& operator=(SelfInfo&& from) noexcept {
    if (GetArenaNoVirtual() == from.GetArenaNoVirtual()) {
      if (this != &from) InternalSwap(&from);
    } else {
      CopyFrom(from);
    }
    return *this;
  }
  #endif
  static const ::google::protobuf::Descriptor* descriptor() {
    return default_instance().GetDescriptor();
  }
  static const SelfInfo& default_instance();

  static void InitAsDefaultInstance();  // FOR INTERNAL USE ONLY
  static inline const SelfInfo* internal_default_instance() {
    return reinterpret_cast<const SelfInfo*>(
               &_SelfInfo_default_instance_);
  }
  static constexpr int kIndexInFileMessages =
    3;

  void Swap(SelfInfo* other);
  friend void swap(SelfInfo& a, SelfInfo& b) {
    a.Swap(&b);
  }

  // implements Message ----------------------------------------------

  inline SelfInfo* New() const final {
    return CreateMaybeMessage<SelfInfo>(nullptr);
  }

  SelfInfo* New(::google::protobuf::Arena* arena) const final {
    return CreateMaybeMessage<SelfInfo>(arena);
  }
  void CopyFrom(const ::google::protobuf::Message& from) final;
  void MergeFrom(const ::google::protobuf::Message& from) final;
  void CopyFrom(const SelfInfo& from);
  void MergeFrom(const SelfInfo& from);
  PROTOBUF_ATTRIBUTE_REINITIALIZES void Clear() final;
  bool IsInitialized() const final;

  size_t ByteSizeLong() const final;
  #if GOOGLE_PROTOBUF_ENABLE_EXPERIMENTAL_PARSER
  static const char* _InternalParse(const char* begin, const char* end, void* object, ::google::protobuf::internal::ParseContext* ctx);
  ::google::protobuf::internal::ParseFunc _ParseFunc() const final { return _InternalParse; }
  #else
  bool MergePartialFromCodedStream(
      ::google::protobuf::io::CodedInputStream* input) final;
  #endif  // GOOGLE_PROTOBUF_ENABLE_EXPERIMENTAL_PARSER
  void SerializeWithCachedSizes(
      ::google::protobuf::io::CodedOutputStream* output) const final;
  ::google::protobuf::uint8* InternalSerializeWithCachedSizesToArray(
      ::google::protobuf::uint8* target) const final;
  int GetCachedSize() const final { return _cached_size_.Get(); }

  private:
  void SharedCtor();
  void SharedDtor();
  void SetCachedSize(int size) const final;
  void InternalSwap(SelfInfo* other);
  private:
  inline ::google::protobuf::Arena* GetArenaNoVirtual() const {
    return nullptr;
  }
  inline void* MaybeArenaPtr() const {
    return nullptr;
  }
  public:

  ::google::protobuf::Metadata GetMetadata() const final;

  // nested types ----------------------------------------------------

  // accessors -------------------------------------------------------

  // repeated .comm_player.Item bag = 11;
  int bag_size() const;
  void clear_bag();
  static const int kBagFieldNumber = 11;
  ::comm_player::Item* mutable_bag(int index);
  ::google::protobuf::RepeatedPtrField< ::comm_player::Item >*
      mutable_bag();
  const ::comm_player::Item& bag(int index) const;
  ::comm_player::Item* add_bag();
  const ::google::protobuf::RepeatedPtrField< ::comm_player::Item >&
      bag() const;

  // .comm_player.XYPosition pos = 10;
  bool has_pos() const;
  void clear_pos();
  static const int kPosFieldNumber = 10;
  const ::comm_player::XYPosition& pos() const;
  ::comm_player::XYPosition* release_pos();
  ::comm_player::XYPosition* mutable_pos();
  void set_allocated_pos(::comm_player::XYPosition* pos);

  // double heal_point = 1;
  void clear_heal_point();
  static const int kHealPointFieldNumber = 1;
  double heal_point() const;
  void set_heal_point(double value);

  // double heal_point_limit = 2;
  void clear_heal_point_limit();
  static const int kHealPointLimitFieldNumber = 2;
  double heal_point_limit() const;
  void set_heal_point_limit(double value);

  // double move_angle = 3;
  void clear_move_angle();
  static const int kMoveAngleFieldNumber = 3;
  double move_angle() const;
  void set_move_angle(double value);

  // double view_angle = 4;
  void clear_view_angle();
  static const int kViewAngleFieldNumber = 4;
  double view_angle() const;
  void set_view_angle(double value);

  // double move_speed = 5;
  void clear_move_speed();
  static const int kMoveSpeedFieldNumber = 5;
  double move_speed() const;
  void set_move_speed(double value);

  // int32 vocation = 6;
  void clear_vocation();
  static const int kVocationFieldNumber = 6;
  ::google::protobuf::int32 vocation() const;
  void set_vocation(::google::protobuf::int32 value);

  // int32 status = 7;
  void clear_status();
  static const int kStatusFieldNumber = 7;
  ::google::protobuf::int32 status() const;
  void set_status(::google::protobuf::int32 value);

  // int32 move_cd = 8;
  void clear_move_cd();
  static const int kMoveCdFieldNumber = 8;
  ::google::protobuf::int32 move_cd() const;
  void set_move_cd(::google::protobuf::int32 value);

  // int32 attack_cd = 9;
  void clear_attack_cd();
  static const int kAttackCdFieldNumber = 9;
  ::google::protobuf::int32 attack_cd() const;
  void set_attack_cd(::google::protobuf::int32 value);

  // double view_width = 12;
  void clear_view_width();
  static const int kViewWidthFieldNumber = 12;
  double view_width() const;
  void set_view_width(double value);

  // double view_distance = 13;
  void clear_view_distance();
  static const int kViewDistanceFieldNumber = 13;
  double view_distance() const;
  void set_view_distance(double value);

  // @@protoc_insertion_point(class_scope:comm_player.SelfInfo)
 private:
  class HasBitSetters;

  ::google::protobuf::internal::InternalMetadataWithArena _internal_metadata_;
  ::google::protobuf::RepeatedPtrField< ::comm_player::Item > bag_;
  ::comm_player::XYPosition* pos_;
  double heal_point_;
  double heal_point_limit_;
  double move_angle_;
  double view_angle_;
  double move_speed_;
  ::google::protobuf::int32 vocation_;
  ::google::protobuf::int32 status_;
  ::google::protobuf::int32 move_cd_;
  ::google::protobuf::int32 attack_cd_;
  double view_width_;
  double view_distance_;
  mutable ::google::protobuf::internal::CachedSize _cached_size_;
  friend struct ::TableStruct_proto_2fcommunication_5fplayer_2eproto;
};
// -------------------------------------------------------------------

class OtherInfo final :
    public ::google::protobuf::Message /* @@protoc_insertion_point(class_definition:comm_player.OtherInfo) */ {
 public:
  OtherInfo();
  virtual ~OtherInfo();

  OtherInfo(const OtherInfo& from);

  inline OtherInfo& operator=(const OtherInfo& from) {
    CopyFrom(from);
    return *this;
  }
  #if LANG_CXX11
  OtherInfo(OtherInfo&& from) noexcept
    : OtherInfo() {
    *this = ::std::move(from);
  }

  inline OtherInfo& operator=(OtherInfo&& from) noexcept {
    if (GetArenaNoVirtual() == from.GetArenaNoVirtual()) {
      if (this != &from) InternalSwap(&from);
    } else {
      CopyFrom(from);
    }
    return *this;
  }
  #endif
  static const ::google::protobuf::Descriptor* descriptor() {
    return default_instance().GetDescriptor();
  }
  static const OtherInfo& default_instance();

  static void InitAsDefaultInstance();  // FOR INTERNAL USE ONLY
  static inline const OtherInfo* internal_default_instance() {
    return reinterpret_cast<const OtherInfo*>(
               &_OtherInfo_default_instance_);
  }
  static constexpr int kIndexInFileMessages =
    4;

  void Swap(OtherInfo* other);
  friend void swap(OtherInfo& a, OtherInfo& b) {
    a.Swap(&b);
  }

  // implements Message ----------------------------------------------

  inline OtherInfo* New() const final {
    return CreateMaybeMessage<OtherInfo>(nullptr);
  }

  OtherInfo* New(::google::protobuf::Arena* arena) const final {
    return CreateMaybeMessage<OtherInfo>(arena);
  }
  void CopyFrom(const ::google::protobuf::Message& from) final;
  void MergeFrom(const ::google::protobuf::Message& from) final;
  void CopyFrom(const OtherInfo& from);
  void MergeFrom(const OtherInfo& from);
  PROTOBUF_ATTRIBUTE_REINITIALIZES void Clear() final;
  bool IsInitialized() const final;

  size_t ByteSizeLong() const final;
  #if GOOGLE_PROTOBUF_ENABLE_EXPERIMENTAL_PARSER
  static const char* _InternalParse(const char* begin, const char* end, void* object, ::google::protobuf::internal::ParseContext* ctx);
  ::google::protobuf::internal::ParseFunc _ParseFunc() const final { return _InternalParse; }
  #else
  bool MergePartialFromCodedStream(
      ::google::protobuf::io::CodedInputStream* input) final;
  #endif  // GOOGLE_PROTOBUF_ENABLE_EXPERIMENTAL_PARSER
  void SerializeWithCachedSizes(
      ::google::protobuf::io::CodedOutputStream* output) const final;
  ::google::protobuf::uint8* InternalSerializeWithCachedSizesToArray(
      ::google::protobuf::uint8* target) const final;
  int GetCachedSize() const final { return _cached_size_.Get(); }

  private:
  void SharedCtor();
  void SharedDtor();
  void SetCachedSize(int size) const final;
  void InternalSwap(OtherInfo* other);
  private:
  inline ::google::protobuf::Arena* GetArenaNoVirtual() const {
    return nullptr;
  }
  inline void* MaybeArenaPtr() const {
    return nullptr;
  }
  public:

  ::google::protobuf::Metadata GetMetadata() const final;

  // nested types ----------------------------------------------------

  // accessors -------------------------------------------------------

  // .comm_player.PolarPosition pos = 7;
  bool has_pos() const;
  void clear_pos();
  static const int kPosFieldNumber = 7;
  const ::comm_player::PolarPosition& pos() const;
  ::comm_player::PolarPosition* release_pos();
  ::comm_player::PolarPosition* mutable_pos();
  void set_allocated_pos(::comm_player::PolarPosition* pos);

  // int32 player_ID = 1;
  void clear_player_id();
  static const int kPlayerIDFieldNumber = 1;
  ::google::protobuf::int32 player_id() const;
  void set_player_id(::google::protobuf::int32 value);

  // int32 status = 2;
  void clear_status();
  static const int kStatusFieldNumber = 2;
  ::google::protobuf::int32 status() const;
  void set_status(::google::protobuf::int32 value);

  // double move_angle = 3;
  void clear_move_angle();
  static const int kMoveAngleFieldNumber = 3;
  double move_angle() const;
  void set_move_angle(double value);

  // double view_angle = 4;
  void clear_view_angle();
  static const int kViewAngleFieldNumber = 4;
  double view_angle() const;
  void set_view_angle(double value);

  // double move_speed = 5;
  void clear_move_speed();
  static const int kMoveSpeedFieldNumber = 5;
  double move_speed() const;
  void set_move_speed(double value);

  // int32 vocation = 6;
  void clear_vocation();
  static const int kVocationFieldNumber = 6;
  ::google::protobuf::int32 vocation() const;
  void set_vocation(::google::protobuf::int32 value);

  // @@protoc_insertion_point(class_scope:comm_player.OtherInfo)
 private:
  class HasBitSetters;

  ::google::protobuf::internal::InternalMetadataWithArena _internal_metadata_;
  ::comm_player::PolarPosition* pos_;
  ::google::protobuf::int32 player_id_;
  ::google::protobuf::int32 status_;
  double move_angle_;
  double view_angle_;
  double move_speed_;
  ::google::protobuf::int32 vocation_;
  mutable ::google::protobuf::internal::CachedSize _cached_size_;
  friend struct ::TableStruct_proto_2fcommunication_5fplayer_2eproto;
};
// -------------------------------------------------------------------

class Sound final :
    public ::google::protobuf::Message /* @@protoc_insertion_point(class_definition:comm_player.Sound) */ {
 public:
  Sound();
  virtual ~Sound();

  Sound(const Sound& from);

  inline Sound& operator=(const Sound& from) {
    CopyFrom(from);
    return *this;
  }
  #if LANG_CXX11
  Sound(Sound&& from) noexcept
    : Sound() {
    *this = ::std::move(from);
  }

  inline Sound& operator=(Sound&& from) noexcept {
    if (GetArenaNoVirtual() == from.GetArenaNoVirtual()) {
      if (this != &from) InternalSwap(&from);
    } else {
      CopyFrom(from);
    }
    return *this;
  }
  #endif
  static const ::google::protobuf::Descriptor* descriptor() {
    return default_instance().GetDescriptor();
  }
  static const Sound& default_instance();

  static void InitAsDefaultInstance();  // FOR INTERNAL USE ONLY
  static inline const Sound* internal_default_instance() {
    return reinterpret_cast<const Sound*>(
               &_Sound_default_instance_);
  }
  static constexpr int kIndexInFileMessages =
    5;

  void Swap(Sound* other);
  friend void swap(Sound& a, Sound& b) {
    a.Swap(&b);
  }

  // implements Message ----------------------------------------------

  inline Sound* New() const final {
    return CreateMaybeMessage<Sound>(nullptr);
  }

  Sound* New(::google::protobuf::Arena* arena) const final {
    return CreateMaybeMessage<Sound>(arena);
  }
  void CopyFrom(const ::google::protobuf::Message& from) final;
  void MergeFrom(const ::google::protobuf::Message& from) final;
  void CopyFrom(const Sound& from);
  void MergeFrom(const Sound& from);
  PROTOBUF_ATTRIBUTE_REINITIALIZES void Clear() final;
  bool IsInitialized() const final;

  size_t ByteSizeLong() const final;
  #if GOOGLE_PROTOBUF_ENABLE_EXPERIMENTAL_PARSER
  static const char* _InternalParse(const char* begin, const char* end, void* object, ::google::protobuf::internal::ParseContext* ctx);
  ::google::protobuf::internal::ParseFunc _ParseFunc() const final { return _InternalParse; }
  #else
  bool MergePartialFromCodedStream(
      ::google::protobuf::io::CodedInputStream* input) final;
  #endif  // GOOGLE_PROTOBUF_ENABLE_EXPERIMENTAL_PARSER
  void SerializeWithCachedSizes(
      ::google::protobuf::io::CodedOutputStream* output) const final;
  ::google::protobuf::uint8* InternalSerializeWithCachedSizesToArray(
      ::google::protobuf::uint8* target) const final;
  int GetCachedSize() const final { return _cached_size_.Get(); }

  private:
  void SharedCtor();
  void SharedDtor();
  void SetCachedSize(int size) const final;
  void InternalSwap(Sound* other);
  private:
  inline ::google::protobuf::Arena* GetArenaNoVirtual() const {
    return nullptr;
  }
  inline void* MaybeArenaPtr() const {
    return nullptr;
  }
  public:

  ::google::protobuf::Metadata GetMetadata() const final;

  // nested types ----------------------------------------------------

  // accessors -------------------------------------------------------

  // int32 sender = 1;
  void clear_sender();
  static const int kSenderFieldNumber = 1;
  ::google::protobuf::int32 sender() const;
  void set_sender(::google::protobuf::int32 value);

  // int32 delay = 2;
  void clear_delay();
  static const int kDelayFieldNumber = 2;
  ::google::protobuf::int32 delay() const;
  void set_delay(::google::protobuf::int32 value);

  // int32 parameter = 3;
  void clear_parameter();
  static const int kParameterFieldNumber = 3;
  ::google::protobuf::int32 parameter() const;
  void set_parameter(::google::protobuf::int32 value);

  // @@protoc_insertion_point(class_scope:comm_player.Sound)
 private:
  class HasBitSetters;

  ::google::protobuf::internal::InternalMetadataWithArena _internal_metadata_;
  ::google::protobuf::int32 sender_;
  ::google::protobuf::int32 delay_;
  ::google::protobuf::int32 parameter_;
  mutable ::google::protobuf::internal::CachedSize _cached_size_;
  friend struct ::TableStruct_proto_2fcommunication_5fplayer_2eproto;
};
// -------------------------------------------------------------------

class PlayerInfo final :
    public ::google::protobuf::Message /* @@protoc_insertion_point(class_definition:comm_player.PlayerInfo) */ {
 public:
  PlayerInfo();
  virtual ~PlayerInfo();

  PlayerInfo(const PlayerInfo& from);

  inline PlayerInfo& operator=(const PlayerInfo& from) {
    CopyFrom(from);
    return *this;
  }
  #if LANG_CXX11
  PlayerInfo(PlayerInfo&& from) noexcept
    : PlayerInfo() {
    *this = ::std::move(from);
  }

  inline PlayerInfo& operator=(PlayerInfo&& from) noexcept {
    if (GetArenaNoVirtual() == from.GetArenaNoVirtual()) {
      if (this != &from) InternalSwap(&from);
    } else {
      CopyFrom(from);
    }
    return *this;
  }
  #endif
  static const ::google::protobuf::Descriptor* descriptor() {
    return default_instance().GetDescriptor();
  }
  static const PlayerInfo& default_instance();

  static void InitAsDefaultInstance();  // FOR INTERNAL USE ONLY
  static inline const PlayerInfo* internal_default_instance() {
    return reinterpret_cast<const PlayerInfo*>(
               &_PlayerInfo_default_instance_);
  }
  static constexpr int kIndexInFileMessages =
    6;

  void Swap(PlayerInfo* other);
  friend void swap(PlayerInfo& a, PlayerInfo& b) {
    a.Swap(&b);
  }

  // implements Message ----------------------------------------------

  inline PlayerInfo* New() const final {
    return CreateMaybeMessage<PlayerInfo>(nullptr);
  }

  PlayerInfo* New(::google::protobuf::Arena* arena) const final {
    return CreateMaybeMessage<PlayerInfo>(arena);
  }
  void CopyFrom(const ::google::protobuf::Message& from) final;
  void MergeFrom(const ::google::protobuf::Message& from) final;
  void CopyFrom(const PlayerInfo& from);
  void MergeFrom(const PlayerInfo& from);
  PROTOBUF_ATTRIBUTE_REINITIALIZES void Clear() final;
  bool IsInitialized() const final;

  size_t ByteSizeLong() const final;
  #if GOOGLE_PROTOBUF_ENABLE_EXPERIMENTAL_PARSER
  static const char* _InternalParse(const char* begin, const char* end, void* object, ::google::protobuf::internal::ParseContext* ctx);
  ::google::protobuf::internal::ParseFunc _ParseFunc() const final { return _InternalParse; }
  #else
  bool MergePartialFromCodedStream(
      ::google::protobuf::io::CodedInputStream* input) final;
  #endif  // GOOGLE_PROTOBUF_ENABLE_EXPERIMENTAL_PARSER
  void SerializeWithCachedSizes(
      ::google::protobuf::io::CodedOutputStream* output) const final;
  ::google::protobuf::uint8* InternalSerializeWithCachedSizesToArray(
      ::google::protobuf::uint8* target) const final;
  int GetCachedSize() const final { return _cached_size_.Get(); }

  private:
  void SharedCtor();
  void SharedDtor();
  void SetCachedSize(int size) const final;
  void InternalSwap(PlayerInfo* other);
  private:
  inline ::google::protobuf::Arena* GetArenaNoVirtual() const {
    return nullptr;
  }
  inline void* MaybeArenaPtr() const {
    return nullptr;
  }
  public:

  ::google::protobuf::Metadata GetMetadata() const final;

  // nested types ----------------------------------------------------

  // accessors -------------------------------------------------------

  // repeated int32 landform_id = 2;
  int landform_id_size() const;
  void clear_landform_id();
  static const int kLandformIdFieldNumber = 2;
  ::google::protobuf::int32 landform_id(int index) const;
  void set_landform_id(int index, ::google::protobuf::int32 value);
  void add_landform_id(::google::protobuf::int32 value);
  const ::google::protobuf::RepeatedField< ::google::protobuf::int32 >&
      landform_id() const;
  ::google::protobuf::RepeatedField< ::google::protobuf::int32 >*
      mutable_landform_id();

  // repeated .comm_player.Item items = 3;
  int items_size() const;
  void clear_items();
  static const int kItemsFieldNumber = 3;
  ::comm_player::Item* mutable_items(int index);
  ::google::protobuf::RepeatedPtrField< ::comm_player::Item >*
      mutable_items();
  const ::comm_player::Item& items(int index) const;
  ::comm_player::Item* add_items();
  const ::google::protobuf::RepeatedPtrField< ::comm_player::Item >&
      items() const;

  // repeated .comm_player.OtherInfo others = 4;
  int others_size() const;
  void clear_others();
  static const int kOthersFieldNumber = 4;
  ::comm_player::OtherInfo* mutable_others(int index);
  ::google::protobuf::RepeatedPtrField< ::comm_player::OtherInfo >*
      mutable_others();
  const ::comm_player::OtherInfo& others(int index) const;
  ::comm_player::OtherInfo* add_others();
  const ::google::protobuf::RepeatedPtrField< ::comm_player::OtherInfo >&
      others() const;

  // repeated .comm_player.Sound sounds = 5;
  int sounds_size() const;
  void clear_sounds();
  static const int kSoundsFieldNumber = 5;
  ::comm_player::Sound* mutable_sounds(int index);
  ::google::protobuf::RepeatedPtrField< ::comm_player::Sound >*
      mutable_sounds();
  const ::comm_player::Sound& sounds(int index) const;
  ::comm_player::Sound* add_sounds();
  const ::google::protobuf::RepeatedPtrField< ::comm_player::Sound >&
      sounds() const;

  // .comm_player.SelfInfo self = 1;
  bool has_self() const;
  void clear_self();
  static const int kSelfFieldNumber = 1;
  const ::comm_player::SelfInfo& self() const;
  ::comm_player::SelfInfo* release_self();
  ::comm_player::SelfInfo* mutable_self();
  void set_allocated_self(::comm_player::SelfInfo* self);

  // int32 player_ID = 6;
  void clear_player_id();
  static const int kPlayerIDFieldNumber = 6;
  ::google::protobuf::int32 player_id() const;
  void set_player_id(::google::protobuf::int32 value);

  // @@protoc_insertion_point(class_scope:comm_player.PlayerInfo)
 private:
  class HasBitSetters;

  ::google::protobuf::internal::InternalMetadataWithArena _internal_metadata_;
  ::google::protobuf::RepeatedField< ::google::protobuf::int32 > landform_id_;
  mutable std::atomic<int> _landform_id_cached_byte_size_;
  ::google::protobuf::RepeatedPtrField< ::comm_player::Item > items_;
  ::google::protobuf::RepeatedPtrField< ::comm_player::OtherInfo > others_;
  ::google::protobuf::RepeatedPtrField< ::comm_player::Sound > sounds_;
  ::comm_player::SelfInfo* self_;
  ::google::protobuf::int32 player_id_;
  mutable ::google::protobuf::internal::CachedSize _cached_size_;
  friend struct ::TableStruct_proto_2fcommunication_5fplayer_2eproto;
};
// -------------------------------------------------------------------

class Command final :
    public ::google::protobuf::Message /* @@protoc_insertion_point(class_definition:comm_player.Command) */ {
 public:
  Command();
  virtual ~Command();

  Command(const Command& from);

  inline Command& operator=(const Command& from) {
    CopyFrom(from);
    return *this;
  }
  #if LANG_CXX11
  Command(Command&& from) noexcept
    : Command() {
    *this = ::std::move(from);
  }

  inline Command& operator=(Command&& from) noexcept {
    if (GetArenaNoVirtual() == from.GetArenaNoVirtual()) {
      if (this != &from) InternalSwap(&from);
    } else {
      CopyFrom(from);
    }
    return *this;
  }
  #endif
  static const ::google::protobuf::Descriptor* descriptor() {
    return default_instance().GetDescriptor();
  }
  static const Command& default_instance();

  static void InitAsDefaultInstance();  // FOR INTERNAL USE ONLY
  static inline const Command* internal_default_instance() {
    return reinterpret_cast<const Command*>(
               &_Command_default_instance_);
  }
  static constexpr int kIndexInFileMessages =
    7;

  void Swap(Command* other);
  friend void swap(Command& a, Command& b) {
    a.Swap(&b);
  }

  // implements Message ----------------------------------------------

  inline Command* New() const final {
    return CreateMaybeMessage<Command>(nullptr);
  }

  Command* New(::google::protobuf::Arena* arena) const final {
    return CreateMaybeMessage<Command>(arena);
  }
  void CopyFrom(const ::google::protobuf::Message& from) final;
  void MergeFrom(const ::google::protobuf::Message& from) final;
  void CopyFrom(const Command& from);
  void MergeFrom(const Command& from);
  PROTOBUF_ATTRIBUTE_REINITIALIZES void Clear() final;
  bool IsInitialized() const final;

  size_t ByteSizeLong() const final;
  #if GOOGLE_PROTOBUF_ENABLE_EXPERIMENTAL_PARSER
  static const char* _InternalParse(const char* begin, const char* end, void* object, ::google::protobuf::internal::ParseContext* ctx);
  ::google::protobuf::internal::ParseFunc _ParseFunc() const final { return _InternalParse; }
  #else
  bool MergePartialFromCodedStream(
      ::google::protobuf::io::CodedInputStream* input) final;
  #endif  // GOOGLE_PROTOBUF_ENABLE_EXPERIMENTAL_PARSER
  void SerializeWithCachedSizes(
      ::google::protobuf::io::CodedOutputStream* output) const final;
  ::google::protobuf::uint8* InternalSerializeWithCachedSizesToArray(
      ::google::protobuf::uint8* target) const final;
  int GetCachedSize() const final { return _cached_size_.Get(); }

  private:
  void SharedCtor();
  void SharedDtor();
  void SetCachedSize(int size) const final;
  void InternalSwap(Command* other);
  private:
  inline ::google::protobuf::Arena* GetArenaNoVirtual() const {
    return nullptr;
  }
  inline void* MaybeArenaPtr() const {
    return nullptr;
  }
  public:

  ::google::protobuf::Metadata GetMetadata() const final;

  // nested types ----------------------------------------------------

  // accessors -------------------------------------------------------

  // .comm_player.CommandType command_type = 1;
  void clear_command_type();
  static const int kCommandTypeFieldNumber = 1;
  ::comm_player::CommandType command_type() const;
  void set_command_type(::comm_player::CommandType value);

  // int32 target_ID = 2;
  void clear_target_id();
  static const int kTargetIDFieldNumber = 2;
  ::google::protobuf::int32 target_id() const;
  void set_target_id(::google::protobuf::int32 value);

  // double move_angle = 3;
  void clear_move_angle();
  static const int kMoveAngleFieldNumber = 3;
  double move_angle() const;
  void set_move_angle(double value);

  // double view_angle = 4;
  void clear_view_angle();
  static const int kViewAngleFieldNumber = 4;
  double view_angle() const;
  void set_view_angle(double value);

  // int32 parameter = 5;
  void clear_parameter();
  static const int kParameterFieldNumber = 5;
  ::google::protobuf::int32 parameter() const;
  void set_parameter(::google::protobuf::int32 value);

  // @@protoc_insertion_point(class_scope:comm_player.Command)
 private:
  class HasBitSetters;

  ::google::protobuf::internal::InternalMetadataWithArena _internal_metadata_;
  int command_type_;
  ::google::protobuf::int32 target_id_;
  double move_angle_;
  double view_angle_;
  ::google::protobuf::int32 parameter_;
  mutable ::google::protobuf::internal::CachedSize _cached_size_;
  friend struct ::TableStruct_proto_2fcommunication_5fplayer_2eproto;
};
// -------------------------------------------------------------------

class Route final :
    public ::google::protobuf::Message /* @@protoc_insertion_point(class_definition:comm_player.Route) */ {
 public:
  Route();
  virtual ~Route();

  Route(const Route& from);

  inline Route& operator=(const Route& from) {
    CopyFrom(from);
    return *this;
  }
  #if LANG_CXX11
  Route(Route&& from) noexcept
    : Route() {
    *this = ::std::move(from);
  }

  inline Route& operator=(Route&& from) noexcept {
    if (GetArenaNoVirtual() == from.GetArenaNoVirtual()) {
      if (this != &from) InternalSwap(&from);
    } else {
      CopyFrom(from);
    }
    return *this;
  }
  #endif
  static const ::google::protobuf::Descriptor* descriptor() {
    return default_instance().GetDescriptor();
  }
  static const Route& default_instance();

  static void InitAsDefaultInstance();  // FOR INTERNAL USE ONLY
  static inline const Route* internal_default_instance() {
    return reinterpret_cast<const Route*>(
               &_Route_default_instance_);
  }
  static constexpr int kIndexInFileMessages =
    8;

  void Swap(Route* other);
  friend void swap(Route& a, Route& b) {
    a.Swap(&b);
  }

  // implements Message ----------------------------------------------

  inline Route* New() const final {
    return CreateMaybeMessage<Route>(nullptr);
  }

  Route* New(::google::protobuf::Arena* arena) const final {
    return CreateMaybeMessage<Route>(arena);
  }
  void CopyFrom(const ::google::protobuf::Message& from) final;
  void MergeFrom(const ::google::protobuf::Message& from) final;
  void CopyFrom(const Route& from);
  void MergeFrom(const Route& from);
  PROTOBUF_ATTRIBUTE_REINITIALIZES void Clear() final;
  bool IsInitialized() const final;

  size_t ByteSizeLong() const final;
  #if GOOGLE_PROTOBUF_ENABLE_EXPERIMENTAL_PARSER
  static const char* _InternalParse(const char* begin, const char* end, void* object, ::google::protobuf::internal::ParseContext* ctx);
  ::google::protobuf::internal::ParseFunc _ParseFunc() const final { return _InternalParse; }
  #else
  bool MergePartialFromCodedStream(
      ::google::protobuf::io::CodedInputStream* input) final;
  #endif  // GOOGLE_PROTOBUF_ENABLE_EXPERIMENTAL_PARSER
  void SerializeWithCachedSizes(
      ::google::protobuf::io::CodedOutputStream* output) const final;
  ::google::protobuf::uint8* InternalSerializeWithCachedSizesToArray(
      ::google::protobuf::uint8* target) const final;
  int GetCachedSize() const final { return _cached_size_.Get(); }

  private:
  void SharedCtor();
  void SharedDtor();
  void SetCachedSize(int size) const final;
  void InternalSwap(Route* other);
  private:
  inline ::google::protobuf::Arena* GetArenaNoVirtual() const {
    return nullptr;
  }
  inline void* MaybeArenaPtr() const {
    return nullptr;
  }
  public:

  ::google::protobuf::Metadata GetMetadata() const final;

  // nested types ----------------------------------------------------

  // accessors -------------------------------------------------------

  // .comm_player.XYPosition start_pos = 1;
  bool has_start_pos() const;
  void clear_start_pos();
  static const int kStartPosFieldNumber = 1;
  const ::comm_player::XYPosition& start_pos() const;
  ::comm_player::XYPosition* release_start_pos();
  ::comm_player::XYPosition* mutable_start_pos();
  void set_allocated_start_pos(::comm_player::XYPosition* start_pos);

  // .comm_player.XYPosition over_pos = 2;
  bool has_over_pos() const;
  void clear_over_pos();
  static const int kOverPosFieldNumber = 2;
  const ::comm_player::XYPosition& over_pos() const;
  ::comm_player::XYPosition* release_over_pos();
  ::comm_player::XYPosition* mutable_over_pos();
  void set_allocated_over_pos(::comm_player::XYPosition* over_pos);

  // @@protoc_insertion_point(class_scope:comm_player.Route)
 private:
  class HasBitSetters;

  ::google::protobuf::internal::InternalMetadataWithArena _internal_metadata_;
  ::comm_player::XYPosition* start_pos_;
  ::comm_player::XYPosition* over_pos_;
  mutable ::google::protobuf::internal::CachedSize _cached_size_;
  friend struct ::TableStruct_proto_2fcommunication_5fplayer_2eproto;
};
// -------------------------------------------------------------------

class Parachute final :
    public ::google::protobuf::Message /* @@protoc_insertion_point(class_definition:comm_player.Parachute) */ {
 public:
  Parachute();
  virtual ~Parachute();

  Parachute(const Parachute& from);

  inline Parachute& operator=(const Parachute& from) {
    CopyFrom(from);
    return *this;
  }
  #if LANG_CXX11
  Parachute(Parachute&& from) noexcept
    : Parachute() {
    *this = ::std::move(from);
  }

  inline Parachute& operator=(Parachute&& from) noexcept {
    if (GetArenaNoVirtual() == from.GetArenaNoVirtual()) {
      if (this != &from) InternalSwap(&from);
    } else {
      CopyFrom(from);
    }
    return *this;
  }
  #endif
  static const ::google::protobuf::Descriptor* descriptor() {
    return default_instance().GetDescriptor();
  }
  static const Parachute& default_instance();

  static void InitAsDefaultInstance();  // FOR INTERNAL USE ONLY
  static inline const Parachute* internal_default_instance() {
    return reinterpret_cast<const Parachute*>(
               &_Parachute_default_instance_);
  }
  static constexpr int kIndexInFileMessages =
    9;

  void Swap(Parachute* other);
  friend void swap(Parachute& a, Parachute& b) {
    a.Swap(&b);
  }

  // implements Message ----------------------------------------------

  inline Parachute* New() const final {
    return CreateMaybeMessage<Parachute>(nullptr);
  }

  Parachute* New(::google::protobuf::Arena* arena) const final {
    return CreateMaybeMessage<Parachute>(arena);
  }
  void CopyFrom(const ::google::protobuf::Message& from) final;
  void MergeFrom(const ::google::protobuf::Message& from) final;
  void CopyFrom(const Parachute& from);
  void MergeFrom(const Parachute& from);
  PROTOBUF_ATTRIBUTE_REINITIALIZES void Clear() final;
  bool IsInitialized() const final;

  size_t ByteSizeLong() const final;
  #if GOOGLE_PROTOBUF_ENABLE_EXPERIMENTAL_PARSER
  static const char* _InternalParse(const char* begin, const char* end, void* object, ::google::protobuf::internal::ParseContext* ctx);
  ::google::protobuf::internal::ParseFunc _ParseFunc() const final { return _InternalParse; }
  #else
  bool MergePartialFromCodedStream(
      ::google::protobuf::io::CodedInputStream* input) final;
  #endif  // GOOGLE_PROTOBUF_ENABLE_EXPERIMENTAL_PARSER
  void SerializeWithCachedSizes(
      ::google::protobuf::io::CodedOutputStream* output) const final;
  ::google::protobuf::uint8* InternalSerializeWithCachedSizesToArray(
      ::google::protobuf::uint8* target) const final;
  int GetCachedSize() const final { return _cached_size_.Get(); }

  private:
  void SharedCtor();
  void SharedDtor();
  void SetCachedSize(int size) const final;
  void InternalSwap(Parachute* other);
  private:
  inline ::google::protobuf::Arena* GetArenaNoVirtual() const {
    return nullptr;
  }
  inline void* MaybeArenaPtr() const {
    return nullptr;
  }
  public:

  ::google::protobuf::Metadata GetMetadata() const final;

  // nested types ----------------------------------------------------

  // accessors -------------------------------------------------------

  // .comm_player.XYPosition landing_point = 2;
  bool has_landing_point() const;
  void clear_landing_point();
  static const int kLandingPointFieldNumber = 2;
  const ::comm_player::XYPosition& landing_point() const;
  ::comm_player::XYPosition* release_landing_point();
  ::comm_player::XYPosition* mutable_landing_point();
  void set_allocated_landing_point(::comm_player::XYPosition* landing_point);

  // int32 role = 1;
  void clear_role();
  static const int kRoleFieldNumber = 1;
  ::google::protobuf::int32 role() const;
  void set_role(::google::protobuf::int32 value);

  // @@protoc_insertion_point(class_scope:comm_player.Parachute)
 private:
  class HasBitSetters;

  ::google::protobuf::internal::InternalMetadataWithArena _internal_metadata_;
  ::comm_player::XYPosition* landing_point_;
  ::google::protobuf::int32 role_;
  mutable ::google::protobuf::internal::CachedSize _cached_size_;
  friend struct ::TableStruct_proto_2fcommunication_5fplayer_2eproto;
};
// ===================================================================


// ===================================================================

#ifdef __GNUC__
  #pragma GCC diagnostic push
  #pragma GCC diagnostic ignored "-Wstrict-aliasing"
#endif  // __GNUC__
// PolarPosition

// double distance = 1;
inline void PolarPosition::clear_distance() {
  distance_ = 0;
}
inline double PolarPosition::distance() const {
  // @@protoc_insertion_point(field_get:comm_player.PolarPosition.distance)
  return distance_;
}
inline void PolarPosition::set_distance(double value) {
  
  distance_ = value;
  // @@protoc_insertion_point(field_set:comm_player.PolarPosition.distance)
}

// double angle = 2;
inline void PolarPosition::clear_angle() {
  angle_ = 0;
}
inline double PolarPosition::angle() const {
  // @@protoc_insertion_point(field_get:comm_player.PolarPosition.angle)
  return angle_;
}
inline void PolarPosition::set_angle(double value) {
  
  angle_ = value;
  // @@protoc_insertion_point(field_set:comm_player.PolarPosition.angle)
}

// -------------------------------------------------------------------

// XYPosition

// double x = 1;
inline void XYPosition::clear_x() {
  x_ = 0;
}
inline double XYPosition::x() const {
  // @@protoc_insertion_point(field_get:comm_player.XYPosition.x)
  return x_;
}
inline void XYPosition::set_x(double value) {
  
  x_ = value;
  // @@protoc_insertion_point(field_set:comm_player.XYPosition.x)
}

// double y = 2;
inline void XYPosition::clear_y() {
  y_ = 0;
}
inline double XYPosition::y() const {
  // @@protoc_insertion_point(field_get:comm_player.XYPosition.y)
  return y_;
}
inline void XYPosition::set_y(double value) {
  
  y_ = value;
  // @@protoc_insertion_point(field_set:comm_player.XYPosition.y)
}

// -------------------------------------------------------------------

// Item

// int32 item_ID = 1;
inline void Item::clear_item_id() {
  item_id_ = 0;
}
inline ::google::protobuf::int32 Item::item_id() const {
  // @@protoc_insertion_point(field_get:comm_player.Item.item_ID)
  return item_id_;
}
inline void Item::set_item_id(::google::protobuf::int32 value) {
  
  item_id_ = value;
  // @@protoc_insertion_point(field_set:comm_player.Item.item_ID)
}

// int32 type = 2;
inline void Item::clear_type() {
  type_ = 0;
}
inline ::google::protobuf::int32 Item::type() const {
  // @@protoc_insertion_point(field_get:comm_player.Item.type)
  return type_;
}
inline void Item::set_type(::google::protobuf::int32 value) {
  
  type_ = value;
  // @@protoc_insertion_point(field_set:comm_player.Item.type)
}

// .comm_player.PolarPosition pos = 3;
inline bool Item::has_pos() const {
  return this != internal_default_instance() && pos_ != nullptr;
}
inline void Item::clear_pos() {
  if (GetArenaNoVirtual() == nullptr && pos_ != nullptr) {
    delete pos_;
  }
  pos_ = nullptr;
}
inline const ::comm_player::PolarPosition& Item::pos() const {
  const ::comm_player::PolarPosition* p = pos_;
  // @@protoc_insertion_point(field_get:comm_player.Item.pos)
  return p != nullptr ? *p : *reinterpret_cast<const ::comm_player::PolarPosition*>(
      &::comm_player::_PolarPosition_default_instance_);
}
inline ::comm_player::PolarPosition* Item::release_pos() {
  // @@protoc_insertion_point(field_release:comm_player.Item.pos)
  
  ::comm_player::PolarPosition* temp = pos_;
  pos_ = nullptr;
  return temp;
}
inline ::comm_player::PolarPosition* Item::mutable_pos() {
  
  if (pos_ == nullptr) {
    auto* p = CreateMaybeMessage<::comm_player::PolarPosition>(GetArenaNoVirtual());
    pos_ = p;
  }
  // @@protoc_insertion_point(field_mutable:comm_player.Item.pos)
  return pos_;
}
inline void Item::set_allocated_pos(::comm_player::PolarPosition* pos) {
  ::google::protobuf::Arena* message_arena = GetArenaNoVirtual();
  if (message_arena == nullptr) {
    delete pos_;
  }
  if (pos) {
    ::google::protobuf::Arena* submessage_arena = nullptr;
    if (message_arena != submessage_arena) {
      pos = ::google::protobuf::internal::GetOwnedMessage(
          message_arena, pos, submessage_arena);
    }
    
  } else {
    
  }
  pos_ = pos;
  // @@protoc_insertion_point(field_set_allocated:comm_player.Item.pos)
}

// int32 durability = 4;
inline void Item::clear_durability() {
  durability_ = 0;
}
inline ::google::protobuf::int32 Item::durability() const {
  // @@protoc_insertion_point(field_get:comm_player.Item.durability)
  return durability_;
}
inline void Item::set_durability(::google::protobuf::int32 value) {
  
  durability_ = value;
  // @@protoc_insertion_point(field_set:comm_player.Item.durability)
}

// -------------------------------------------------------------------

// SelfInfo

// double heal_point = 1;
inline void SelfInfo::clear_heal_point() {
  heal_point_ = 0;
}
inline double SelfInfo::heal_point() const {
  // @@protoc_insertion_point(field_get:comm_player.SelfInfo.heal_point)
  return heal_point_;
}
inline void SelfInfo::set_heal_point(double value) {
  
  heal_point_ = value;
  // @@protoc_insertion_point(field_set:comm_player.SelfInfo.heal_point)
}

// double heal_point_limit = 2;
inline void SelfInfo::clear_heal_point_limit() {
  heal_point_limit_ = 0;
}
inline double SelfInfo::heal_point_limit() const {
  // @@protoc_insertion_point(field_get:comm_player.SelfInfo.heal_point_limit)
  return heal_point_limit_;
}
inline void SelfInfo::set_heal_point_limit(double value) {
  
  heal_point_limit_ = value;
  // @@protoc_insertion_point(field_set:comm_player.SelfInfo.heal_point_limit)
}

// double move_angle = 3;
inline void SelfInfo::clear_move_angle() {
  move_angle_ = 0;
}
inline double SelfInfo::move_angle() const {
  // @@protoc_insertion_point(field_get:comm_player.SelfInfo.move_angle)
  return move_angle_;
}
inline void SelfInfo::set_move_angle(double value) {
  
  move_angle_ = value;
  // @@protoc_insertion_point(field_set:comm_player.SelfInfo.move_angle)
}

// double view_angle = 4;
inline void SelfInfo::clear_view_angle() {
  view_angle_ = 0;
}
inline double SelfInfo::view_angle() const {
  // @@protoc_insertion_point(field_get:comm_player.SelfInfo.view_angle)
  return view_angle_;
}
inline void SelfInfo::set_view_angle(double value) {
  
  view_angle_ = value;
  // @@protoc_insertion_point(field_set:comm_player.SelfInfo.view_angle)
}

// double move_speed = 5;
inline void SelfInfo::clear_move_speed() {
  move_speed_ = 0;
}
inline double SelfInfo::move_speed() const {
  // @@protoc_insertion_point(field_get:comm_player.SelfInfo.move_speed)
  return move_speed_;
}
inline void SelfInfo::set_move_speed(double value) {
  
  move_speed_ = value;
  // @@protoc_insertion_point(field_set:comm_player.SelfInfo.move_speed)
}

// int32 vocation = 6;
inline void SelfInfo::clear_vocation() {
  vocation_ = 0;
}
inline ::google::protobuf::int32 SelfInfo::vocation() const {
  // @@protoc_insertion_point(field_get:comm_player.SelfInfo.vocation)
  return vocation_;
}
inline void SelfInfo::set_vocation(::google::protobuf::int32 value) {
  
  vocation_ = value;
  // @@protoc_insertion_point(field_set:comm_player.SelfInfo.vocation)
}

// int32 status = 7;
inline void SelfInfo::clear_status() {
  status_ = 0;
}
inline ::google::protobuf::int32 SelfInfo::status() const {
  // @@protoc_insertion_point(field_get:comm_player.SelfInfo.status)
  return status_;
}
inline void SelfInfo::set_status(::google::protobuf::int32 value) {
  
  status_ = value;
  // @@protoc_insertion_point(field_set:comm_player.SelfInfo.status)
}

// int32 move_cd = 8;
inline void SelfInfo::clear_move_cd() {
  move_cd_ = 0;
}
inline ::google::protobuf::int32 SelfInfo::move_cd() const {
  // @@protoc_insertion_point(field_get:comm_player.SelfInfo.move_cd)
  return move_cd_;
}
inline void SelfInfo::set_move_cd(::google::protobuf::int32 value) {
  
  move_cd_ = value;
  // @@protoc_insertion_point(field_set:comm_player.SelfInfo.move_cd)
}

// int32 attack_cd = 9;
inline void SelfInfo::clear_attack_cd() {
  attack_cd_ = 0;
}
inline ::google::protobuf::int32 SelfInfo::attack_cd() const {
  // @@protoc_insertion_point(field_get:comm_player.SelfInfo.attack_cd)
  return attack_cd_;
}
inline void SelfInfo::set_attack_cd(::google::protobuf::int32 value) {
  
  attack_cd_ = value;
  // @@protoc_insertion_point(field_set:comm_player.SelfInfo.attack_cd)
}

// .comm_player.XYPosition pos = 10;
inline bool SelfInfo::has_pos() const {
  return this != internal_default_instance() && pos_ != nullptr;
}
inline void SelfInfo::clear_pos() {
  if (GetArenaNoVirtual() == nullptr && pos_ != nullptr) {
    delete pos_;
  }
  pos_ = nullptr;
}
inline const ::comm_player::XYPosition& SelfInfo::pos() const {
  const ::comm_player::XYPosition* p = pos_;
  // @@protoc_insertion_point(field_get:comm_player.SelfInfo.pos)
  return p != nullptr ? *p : *reinterpret_cast<const ::comm_player::XYPosition*>(
      &::comm_player::_XYPosition_default_instance_);
}
inline ::comm_player::XYPosition* SelfInfo::release_pos() {
  // @@protoc_insertion_point(field_release:comm_player.SelfInfo.pos)
  
  ::comm_player::XYPosition* temp = pos_;
  pos_ = nullptr;
  return temp;
}
inline ::comm_player::XYPosition* SelfInfo::mutable_pos() {
  
  if (pos_ == nullptr) {
    auto* p = CreateMaybeMessage<::comm_player::XYPosition>(GetArenaNoVirtual());
    pos_ = p;
  }
  // @@protoc_insertion_point(field_mutable:comm_player.SelfInfo.pos)
  return pos_;
}
inline void SelfInfo::set_allocated_pos(::comm_player::XYPosition* pos) {
  ::google::protobuf::Arena* message_arena = GetArenaNoVirtual();
  if (message_arena == nullptr) {
    delete pos_;
  }
  if (pos) {
    ::google::protobuf::Arena* submessage_arena = nullptr;
    if (message_arena != submessage_arena) {
      pos = ::google::protobuf::internal::GetOwnedMessage(
          message_arena, pos, submessage_arena);
    }
    
  } else {
    
  }
  pos_ = pos;
  // @@protoc_insertion_point(field_set_allocated:comm_player.SelfInfo.pos)
}

// repeated .comm_player.Item bag = 11;
inline int SelfInfo::bag_size() const {
  return bag_.size();
}
inline void SelfInfo::clear_bag() {
  bag_.Clear();
}
inline ::comm_player::Item* SelfInfo::mutable_bag(int index) {
  // @@protoc_insertion_point(field_mutable:comm_player.SelfInfo.bag)
  return bag_.Mutable(index);
}
inline ::google::protobuf::RepeatedPtrField< ::comm_player::Item >*
SelfInfo::mutable_bag() {
  // @@protoc_insertion_point(field_mutable_list:comm_player.SelfInfo.bag)
  return &bag_;
}
inline const ::comm_player::Item& SelfInfo::bag(int index) const {
  // @@protoc_insertion_point(field_get:comm_player.SelfInfo.bag)
  return bag_.Get(index);
}
inline ::comm_player::Item* SelfInfo::add_bag() {
  // @@protoc_insertion_point(field_add:comm_player.SelfInfo.bag)
  return bag_.Add();
}
inline const ::google::protobuf::RepeatedPtrField< ::comm_player::Item >&
SelfInfo::bag() const {
  // @@protoc_insertion_point(field_list:comm_player.SelfInfo.bag)
  return bag_;
}

// double view_width = 12;
inline void SelfInfo::clear_view_width() {
  view_width_ = 0;
}
inline double SelfInfo::view_width() const {
  // @@protoc_insertion_point(field_get:comm_player.SelfInfo.view_width)
  return view_width_;
}
inline void SelfInfo::set_view_width(double value) {
  
  view_width_ = value;
  // @@protoc_insertion_point(field_set:comm_player.SelfInfo.view_width)
}

// double view_distance = 13;
inline void SelfInfo::clear_view_distance() {
  view_distance_ = 0;
}
inline double SelfInfo::view_distance() const {
  // @@protoc_insertion_point(field_get:comm_player.SelfInfo.view_distance)
  return view_distance_;
}
inline void SelfInfo::set_view_distance(double value) {
  
  view_distance_ = value;
  // @@protoc_insertion_point(field_set:comm_player.SelfInfo.view_distance)
}

// -------------------------------------------------------------------

// OtherInfo

// int32 player_ID = 1;
inline void OtherInfo::clear_player_id() {
  player_id_ = 0;
}
inline ::google::protobuf::int32 OtherInfo::player_id() const {
  // @@protoc_insertion_point(field_get:comm_player.OtherInfo.player_ID)
  return player_id_;
}
inline void OtherInfo::set_player_id(::google::protobuf::int32 value) {
  
  player_id_ = value;
  // @@protoc_insertion_point(field_set:comm_player.OtherInfo.player_ID)
}

// int32 status = 2;
inline void OtherInfo::clear_status() {
  status_ = 0;
}
inline ::google::protobuf::int32 OtherInfo::status() const {
  // @@protoc_insertion_point(field_get:comm_player.OtherInfo.status)
  return status_;
}
inline void OtherInfo::set_status(::google::protobuf::int32 value) {
  
  status_ = value;
  // @@protoc_insertion_point(field_set:comm_player.OtherInfo.status)
}

// double move_angle = 3;
inline void OtherInfo::clear_move_angle() {
  move_angle_ = 0;
}
inline double OtherInfo::move_angle() const {
  // @@protoc_insertion_point(field_get:comm_player.OtherInfo.move_angle)
  return move_angle_;
}
inline void OtherInfo::set_move_angle(double value) {
  
  move_angle_ = value;
  // @@protoc_insertion_point(field_set:comm_player.OtherInfo.move_angle)
}

// double view_angle = 4;
inline void OtherInfo::clear_view_angle() {
  view_angle_ = 0;
}
inline double OtherInfo::view_angle() const {
  // @@protoc_insertion_point(field_get:comm_player.OtherInfo.view_angle)
  return view_angle_;
}
inline void OtherInfo::set_view_angle(double value) {
  
  view_angle_ = value;
  // @@protoc_insertion_point(field_set:comm_player.OtherInfo.view_angle)
}

// double move_speed = 5;
inline void OtherInfo::clear_move_speed() {
  move_speed_ = 0;
}
inline double OtherInfo::move_speed() const {
  // @@protoc_insertion_point(field_get:comm_player.OtherInfo.move_speed)
  return move_speed_;
}
inline void OtherInfo::set_move_speed(double value) {
  
  move_speed_ = value;
  // @@protoc_insertion_point(field_set:comm_player.OtherInfo.move_speed)
}

// int32 vocation = 6;
inline void OtherInfo::clear_vocation() {
  vocation_ = 0;
}
inline ::google::protobuf::int32 OtherInfo::vocation() const {
  // @@protoc_insertion_point(field_get:comm_player.OtherInfo.vocation)
  return vocation_;
}
inline void OtherInfo::set_vocation(::google::protobuf::int32 value) {
  
  vocation_ = value;
  // @@protoc_insertion_point(field_set:comm_player.OtherInfo.vocation)
}

// .comm_player.PolarPosition pos = 7;
inline bool OtherInfo::has_pos() const {
  return this != internal_default_instance() && pos_ != nullptr;
}
inline void OtherInfo::clear_pos() {
  if (GetArenaNoVirtual() == nullptr && pos_ != nullptr) {
    delete pos_;
  }
  pos_ = nullptr;
}
inline const ::comm_player::PolarPosition& OtherInfo::pos() const {
  const ::comm_player::PolarPosition* p = pos_;
  // @@protoc_insertion_point(field_get:comm_player.OtherInfo.pos)
  return p != nullptr ? *p : *reinterpret_cast<const ::comm_player::PolarPosition*>(
      &::comm_player::_PolarPosition_default_instance_);
}
inline ::comm_player::PolarPosition* OtherInfo::release_pos() {
  // @@protoc_insertion_point(field_release:comm_player.OtherInfo.pos)
  
  ::comm_player::PolarPosition* temp = pos_;
  pos_ = nullptr;
  return temp;
}
inline ::comm_player::PolarPosition* OtherInfo::mutable_pos() {
  
  if (pos_ == nullptr) {
    auto* p = CreateMaybeMessage<::comm_player::PolarPosition>(GetArenaNoVirtual());
    pos_ = p;
  }
  // @@protoc_insertion_point(field_mutable:comm_player.OtherInfo.pos)
  return pos_;
}
inline void OtherInfo::set_allocated_pos(::comm_player::PolarPosition* pos) {
  ::google::protobuf::Arena* message_arena = GetArenaNoVirtual();
  if (message_arena == nullptr) {
    delete pos_;
  }
  if (pos) {
    ::google::protobuf::Arena* submessage_arena = nullptr;
    if (message_arena != submessage_arena) {
      pos = ::google::protobuf::internal::GetOwnedMessage(
          message_arena, pos, submessage_arena);
    }
    
  } else {
    
  }
  pos_ = pos;
  // @@protoc_insertion_point(field_set_allocated:comm_player.OtherInfo.pos)
}

// -------------------------------------------------------------------

// Sound

// int32 sender = 1;
inline void Sound::clear_sender() {
  sender_ = 0;
}
inline ::google::protobuf::int32 Sound::sender() const {
  // @@protoc_insertion_point(field_get:comm_player.Sound.sender)
  return sender_;
}
inline void Sound::set_sender(::google::protobuf::int32 value) {
  
  sender_ = value;
  // @@protoc_insertion_point(field_set:comm_player.Sound.sender)
}

// int32 delay = 2;
inline void Sound::clear_delay() {
  delay_ = 0;
}
inline ::google::protobuf::int32 Sound::delay() const {
  // @@protoc_insertion_point(field_get:comm_player.Sound.delay)
  return delay_;
}
inline void Sound::set_delay(::google::protobuf::int32 value) {
  
  delay_ = value;
  // @@protoc_insertion_point(field_set:comm_player.Sound.delay)
}

// int32 parameter = 3;
inline void Sound::clear_parameter() {
  parameter_ = 0;
}
inline ::google::protobuf::int32 Sound::parameter() const {
  // @@protoc_insertion_point(field_get:comm_player.Sound.parameter)
  return parameter_;
}
inline void Sound::set_parameter(::google::protobuf::int32 value) {
  
  parameter_ = value;
  // @@protoc_insertion_point(field_set:comm_player.Sound.parameter)
}

// -------------------------------------------------------------------

// PlayerInfo

// int32 player_ID = 6;
inline void PlayerInfo::clear_player_id() {
  player_id_ = 0;
}
inline ::google::protobuf::int32 PlayerInfo::player_id() const {
  // @@protoc_insertion_point(field_get:comm_player.PlayerInfo.player_ID)
  return player_id_;
}
inline void PlayerInfo::set_player_id(::google::protobuf::int32 value) {
  
  player_id_ = value;
  // @@protoc_insertion_point(field_set:comm_player.PlayerInfo.player_ID)
}

// .comm_player.SelfInfo self = 1;
inline bool PlayerInfo::has_self() const {
  return this != internal_default_instance() && self_ != nullptr;
}
inline void PlayerInfo::clear_self() {
  if (GetArenaNoVirtual() == nullptr && self_ != nullptr) {
    delete self_;
  }
  self_ = nullptr;
}
inline const ::comm_player::SelfInfo& PlayerInfo::self() const {
  const ::comm_player::SelfInfo* p = self_;
  // @@protoc_insertion_point(field_get:comm_player.PlayerInfo.self)
  return p != nullptr ? *p : *reinterpret_cast<const ::comm_player::SelfInfo*>(
      &::comm_player::_SelfInfo_default_instance_);
}
inline ::comm_player::SelfInfo* PlayerInfo::release_self() {
  // @@protoc_insertion_point(field_release:comm_player.PlayerInfo.self)
  
  ::comm_player::SelfInfo* temp = self_;
  self_ = nullptr;
  return temp;
}
inline ::comm_player::SelfInfo* PlayerInfo::mutable_self() {
  
  if (self_ == nullptr) {
    auto* p = CreateMaybeMessage<::comm_player::SelfInfo>(GetArenaNoVirtual());
    self_ = p;
  }
  // @@protoc_insertion_point(field_mutable:comm_player.PlayerInfo.self)
  return self_;
}
inline void PlayerInfo::set_allocated_self(::comm_player::SelfInfo* self) {
  ::google::protobuf::Arena* message_arena = GetArenaNoVirtual();
  if (message_arena == nullptr) {
    delete self_;
  }
  if (self) {
    ::google::protobuf::Arena* submessage_arena = nullptr;
    if (message_arena != submessage_arena) {
      self = ::google::protobuf::internal::GetOwnedMessage(
          message_arena, self, submessage_arena);
    }
    
  } else {
    
  }
  self_ = self;
  // @@protoc_insertion_point(field_set_allocated:comm_player.PlayerInfo.self)
}

// repeated int32 landform_id = 2;
inline int PlayerInfo::landform_id_size() const {
  return landform_id_.size();
}
inline void PlayerInfo::clear_landform_id() {
  landform_id_.Clear();
}
inline ::google::protobuf::int32 PlayerInfo::landform_id(int index) const {
  // @@protoc_insertion_point(field_get:comm_player.PlayerInfo.landform_id)
  return landform_id_.Get(index);
}
inline void PlayerInfo::set_landform_id(int index, ::google::protobuf::int32 value) {
  landform_id_.Set(index, value);
  // @@protoc_insertion_point(field_set:comm_player.PlayerInfo.landform_id)
}
inline void PlayerInfo::add_landform_id(::google::protobuf::int32 value) {
  landform_id_.Add(value);
  // @@protoc_insertion_point(field_add:comm_player.PlayerInfo.landform_id)
}
inline const ::google::protobuf::RepeatedField< ::google::protobuf::int32 >&
PlayerInfo::landform_id() const {
  // @@protoc_insertion_point(field_list:comm_player.PlayerInfo.landform_id)
  return landform_id_;
}
inline ::google::protobuf::RepeatedField< ::google::protobuf::int32 >*
PlayerInfo::mutable_landform_id() {
  // @@protoc_insertion_point(field_mutable_list:comm_player.PlayerInfo.landform_id)
  return &landform_id_;
}

// repeated .comm_player.Item items = 3;
inline int PlayerInfo::items_size() const {
  return items_.size();
}
inline void PlayerInfo::clear_items() {
  items_.Clear();
}
inline ::comm_player::Item* PlayerInfo::mutable_items(int index) {
  // @@protoc_insertion_point(field_mutable:comm_player.PlayerInfo.items)
  return items_.Mutable(index);
}
inline ::google::protobuf::RepeatedPtrField< ::comm_player::Item >*
PlayerInfo::mutable_items() {
  // @@protoc_insertion_point(field_mutable_list:comm_player.PlayerInfo.items)
  return &items_;
}
inline const ::comm_player::Item& PlayerInfo::items(int index) const {
  // @@protoc_insertion_point(field_get:comm_player.PlayerInfo.items)
  return items_.Get(index);
}
inline ::comm_player::Item* PlayerInfo::add_items() {
  // @@protoc_insertion_point(field_add:comm_player.PlayerInfo.items)
  return items_.Add();
}
inline const ::google::protobuf::RepeatedPtrField< ::comm_player::Item >&
PlayerInfo::items() const {
  // @@protoc_insertion_point(field_list:comm_player.PlayerInfo.items)
  return items_;
}

// repeated .comm_player.OtherInfo others = 4;
inline int PlayerInfo::others_size() const {
  return others_.size();
}
inline void PlayerInfo::clear_others() {
  others_.Clear();
}
inline ::comm_player::OtherInfo* PlayerInfo::mutable_others(int index) {
  // @@protoc_insertion_point(field_mutable:comm_player.PlayerInfo.others)
  return others_.Mutable(index);
}
inline ::google::protobuf::RepeatedPtrField< ::comm_player::OtherInfo >*
PlayerInfo::mutable_others() {
  // @@protoc_insertion_point(field_mutable_list:comm_player.PlayerInfo.others)
  return &others_;
}
inline const ::comm_player::OtherInfo& PlayerInfo::others(int index) const {
  // @@protoc_insertion_point(field_get:comm_player.PlayerInfo.others)
  return others_.Get(index);
}
inline ::comm_player::OtherInfo* PlayerInfo::add_others() {
  // @@protoc_insertion_point(field_add:comm_player.PlayerInfo.others)
  return others_.Add();
}
inline const ::google::protobuf::RepeatedPtrField< ::comm_player::OtherInfo >&
PlayerInfo::others() const {
  // @@protoc_insertion_point(field_list:comm_player.PlayerInfo.others)
  return others_;
}

// repeated .comm_player.Sound sounds = 5;
inline int PlayerInfo::sounds_size() const {
  return sounds_.size();
}
inline void PlayerInfo::clear_sounds() {
  sounds_.Clear();
}
inline ::comm_player::Sound* PlayerInfo::mutable_sounds(int index) {
  // @@protoc_insertion_point(field_mutable:comm_player.PlayerInfo.sounds)
  return sounds_.Mutable(index);
}
inline ::google::protobuf::RepeatedPtrField< ::comm_player::Sound >*
PlayerInfo::mutable_sounds() {
  // @@protoc_insertion_point(field_mutable_list:comm_player.PlayerInfo.sounds)
  return &sounds_;
}
inline const ::comm_player::Sound& PlayerInfo::sounds(int index) const {
  // @@protoc_insertion_point(field_get:comm_player.PlayerInfo.sounds)
  return sounds_.Get(index);
}
inline ::comm_player::Sound* PlayerInfo::add_sounds() {
  // @@protoc_insertion_point(field_add:comm_player.PlayerInfo.sounds)
  return sounds_.Add();
}
inline const ::google::protobuf::RepeatedPtrField< ::comm_player::Sound >&
PlayerInfo::sounds() const {
  // @@protoc_insertion_point(field_list:comm_player.PlayerInfo.sounds)
  return sounds_;
}

// -------------------------------------------------------------------

// Command

// .comm_player.CommandType command_type = 1;
inline void Command::clear_command_type() {
  command_type_ = 0;
}
inline ::comm_player::CommandType Command::command_type() const {
  // @@protoc_insertion_point(field_get:comm_player.Command.command_type)
  return static_cast< ::comm_player::CommandType >(command_type_);
}
inline void Command::set_command_type(::comm_player::CommandType value) {
  
  command_type_ = value;
  // @@protoc_insertion_point(field_set:comm_player.Command.command_type)
}

// int32 target_ID = 2;
inline void Command::clear_target_id() {
  target_id_ = 0;
}
inline ::google::protobuf::int32 Command::target_id() const {
  // @@protoc_insertion_point(field_get:comm_player.Command.target_ID)
  return target_id_;
}
inline void Command::set_target_id(::google::protobuf::int32 value) {
  
  target_id_ = value;
  // @@protoc_insertion_point(field_set:comm_player.Command.target_ID)
}

// double move_angle = 3;
inline void Command::clear_move_angle() {
  move_angle_ = 0;
}
inline double Command::move_angle() const {
  // @@protoc_insertion_point(field_get:comm_player.Command.move_angle)
  return move_angle_;
}
inline void Command::set_move_angle(double value) {
  
  move_angle_ = value;
  // @@protoc_insertion_point(field_set:comm_player.Command.move_angle)
}

// double view_angle = 4;
inline void Command::clear_view_angle() {
  view_angle_ = 0;
}
inline double Command::view_angle() const {
  // @@protoc_insertion_point(field_get:comm_player.Command.view_angle)
  return view_angle_;
}
inline void Command::set_view_angle(double value) {
  
  view_angle_ = value;
  // @@protoc_insertion_point(field_set:comm_player.Command.view_angle)
}

// int32 parameter = 5;
inline void Command::clear_parameter() {
  parameter_ = 0;
}
inline ::google::protobuf::int32 Command::parameter() const {
  // @@protoc_insertion_point(field_get:comm_player.Command.parameter)
  return parameter_;
}
inline void Command::set_parameter(::google::protobuf::int32 value) {
  
  parameter_ = value;
  // @@protoc_insertion_point(field_set:comm_player.Command.parameter)
}

// -------------------------------------------------------------------

// Route

// .comm_player.XYPosition start_pos = 1;
inline bool Route::has_start_pos() const {
  return this != internal_default_instance() && start_pos_ != nullptr;
}
inline void Route::clear_start_pos() {
  if (GetArenaNoVirtual() == nullptr && start_pos_ != nullptr) {
    delete start_pos_;
  }
  start_pos_ = nullptr;
}
inline const ::comm_player::XYPosition& Route::start_pos() const {
  const ::comm_player::XYPosition* p = start_pos_;
  // @@protoc_insertion_point(field_get:comm_player.Route.start_pos)
  return p != nullptr ? *p : *reinterpret_cast<const ::comm_player::XYPosition*>(
      &::comm_player::_XYPosition_default_instance_);
}
inline ::comm_player::XYPosition* Route::release_start_pos() {
  // @@protoc_insertion_point(field_release:comm_player.Route.start_pos)
  
  ::comm_player::XYPosition* temp = start_pos_;
  start_pos_ = nullptr;
  return temp;
}
inline ::comm_player::XYPosition* Route::mutable_start_pos() {
  
  if (start_pos_ == nullptr) {
    auto* p = CreateMaybeMessage<::comm_player::XYPosition>(GetArenaNoVirtual());
    start_pos_ = p;
  }
  // @@protoc_insertion_point(field_mutable:comm_player.Route.start_pos)
  return start_pos_;
}
inline void Route::set_allocated_start_pos(::comm_player::XYPosition* start_pos) {
  ::google::protobuf::Arena* message_arena = GetArenaNoVirtual();
  if (message_arena == nullptr) {
    delete start_pos_;
  }
  if (start_pos) {
    ::google::protobuf::Arena* submessage_arena = nullptr;
    if (message_arena != submessage_arena) {
      start_pos = ::google::protobuf::internal::GetOwnedMessage(
          message_arena, start_pos, submessage_arena);
    }
    
  } else {
    
  }
  start_pos_ = start_pos;
  // @@protoc_insertion_point(field_set_allocated:comm_player.Route.start_pos)
}

// .comm_player.XYPosition over_pos = 2;
inline bool Route::has_over_pos() const {
  return this != internal_default_instance() && over_pos_ != nullptr;
}
inline void Route::clear_over_pos() {
  if (GetArenaNoVirtual() == nullptr && over_pos_ != nullptr) {
    delete over_pos_;
  }
  over_pos_ = nullptr;
}
inline const ::comm_player::XYPosition& Route::over_pos() const {
  const ::comm_player::XYPosition* p = over_pos_;
  // @@protoc_insertion_point(field_get:comm_player.Route.over_pos)
  return p != nullptr ? *p : *reinterpret_cast<const ::comm_player::XYPosition*>(
      &::comm_player::_XYPosition_default_instance_);
}
inline ::comm_player::XYPosition* Route::release_over_pos() {
  // @@protoc_insertion_point(field_release:comm_player.Route.over_pos)
  
  ::comm_player::XYPosition* temp = over_pos_;
  over_pos_ = nullptr;
  return temp;
}
inline ::comm_player::XYPosition* Route::mutable_over_pos() {
  
  if (over_pos_ == nullptr) {
    auto* p = CreateMaybeMessage<::comm_player::XYPosition>(GetArenaNoVirtual());
    over_pos_ = p;
  }
  // @@protoc_insertion_point(field_mutable:comm_player.Route.over_pos)
  return over_pos_;
}
inline void Route::set_allocated_over_pos(::comm_player::XYPosition* over_pos) {
  ::google::protobuf::Arena* message_arena = GetArenaNoVirtual();
  if (message_arena == nullptr) {
    delete over_pos_;
  }
  if (over_pos) {
    ::google::protobuf::Arena* submessage_arena = nullptr;
    if (message_arena != submessage_arena) {
      over_pos = ::google::protobuf::internal::GetOwnedMessage(
          message_arena, over_pos, submessage_arena);
    }
    
  } else {
    
  }
  over_pos_ = over_pos;
  // @@protoc_insertion_point(field_set_allocated:comm_player.Route.over_pos)
}

// -------------------------------------------------------------------

// Parachute

// int32 role = 1;
inline void Parachute::clear_role() {
  role_ = 0;
}
inline ::google::protobuf::int32 Parachute::role() const {
  // @@protoc_insertion_point(field_get:comm_player.Parachute.role)
  return role_;
}
inline void Parachute::set_role(::google::protobuf::int32 value) {
  
  role_ = value;
  // @@protoc_insertion_point(field_set:comm_player.Parachute.role)
}

// .comm_player.XYPosition landing_point = 2;
inline bool Parachute::has_landing_point() const {
  return this != internal_default_instance() && landing_point_ != nullptr;
}
inline void Parachute::clear_landing_point() {
  if (GetArenaNoVirtual() == nullptr && landing_point_ != nullptr) {
    delete landing_point_;
  }
  landing_point_ = nullptr;
}
inline const ::comm_player::XYPosition& Parachute::landing_point() const {
  const ::comm_player::XYPosition* p = landing_point_;
  // @@protoc_insertion_point(field_get:comm_player.Parachute.landing_point)
  return p != nullptr ? *p : *reinterpret_cast<const ::comm_player::XYPosition*>(
      &::comm_player::_XYPosition_default_instance_);
}
inline ::comm_player::XYPosition* Parachute::release_landing_point() {
  // @@protoc_insertion_point(field_release:comm_player.Parachute.landing_point)
  
  ::comm_player::XYPosition* temp = landing_point_;
  landing_point_ = nullptr;
  return temp;
}
inline ::comm_player::XYPosition* Parachute::mutable_landing_point() {
  
  if (landing_point_ == nullptr) {
    auto* p = CreateMaybeMessage<::comm_player::XYPosition>(GetArenaNoVirtual());
    landing_point_ = p;
  }
  // @@protoc_insertion_point(field_mutable:comm_player.Parachute.landing_point)
  return landing_point_;
}
inline void Parachute::set_allocated_landing_point(::comm_player::XYPosition* landing_point) {
  ::google::protobuf::Arena* message_arena = GetArenaNoVirtual();
  if (message_arena == nullptr) {
    delete landing_point_;
  }
  if (landing_point) {
    ::google::protobuf::Arena* submessage_arena = nullptr;
    if (message_arena != submessage_arena) {
      landing_point = ::google::protobuf::internal::GetOwnedMessage(
          message_arena, landing_point, submessage_arena);
    }
    
  } else {
    
  }
  landing_point_ = landing_point;
  // @@protoc_insertion_point(field_set_allocated:comm_player.Parachute.landing_point)
}

#ifdef __GNUC__
  #pragma GCC diagnostic pop
#endif  // __GNUC__
// -------------------------------------------------------------------

// -------------------------------------------------------------------

// -------------------------------------------------------------------

// -------------------------------------------------------------------

// -------------------------------------------------------------------

// -------------------------------------------------------------------

// -------------------------------------------------------------------

// -------------------------------------------------------------------

// -------------------------------------------------------------------


// @@protoc_insertion_point(namespace_scope)

}  // namespace comm_player

namespace google {
namespace protobuf {

template <> struct is_proto_enum< ::comm_player::CommandType> : ::std::true_type {};
template <>
inline const EnumDescriptor* GetEnumDescriptor< ::comm_player::CommandType>() {
  return ::comm_player::CommandType_descriptor();
}

}  // namespace protobuf
}  // namespace google

// @@protoc_insertion_point(global_scope)

#include <google/protobuf/port_undef.inc>
#endif  // PROTOBUF_INCLUDED_proto_2fcommunication_5fplayer_2eproto
