# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: interface.proto

import sys
_b=sys.version_info[0]<3 and (lambda x:x) or (lambda x:x.encode('latin1'))
from google.protobuf import descriptor as _descriptor
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor.FileDescriptor(
  name='interface.proto',
  package='logic_to_interface',
  syntax='proto3',
  serialized_options=None,
  serialized_pb=_b('\n\x0finterface.proto\x12\x12logic_to_interface\"\x1b\n\x03Pos\x12\t\n\x01x\x18\x01 \x01(\x01\x12\t\n\x01y\x18\x02 \x01(\x01\"M\n\x0fPlayerBasicInfo\x12\n\n\x02id\x18\x01 \x01(\x05\x12\x0c\n\x04team\x18\x02 \x01(\x05\x12\x10\n\x08vocation\x18\x03 \x01(\x05\x12\x0e\n\x06HP_max\x18\x04 \x01(\x05\"\xc1\x01\n\x13PlayerParachuteInfo\x12\n\n\x02id\x18\x01 \x01(\x05\x12\n\n\x02HP\x18\x02 \x01(\x05\x12\x16\n\x0e\x66\x61\x63\x65_direction\x18\x03 \x01(\x01\x12$\n\x03pos\x18\x04 \x01(\x0b\x32\x17.logic_to_interface.Pos\x12)\n\x08jump_pos\x18\x05 \x01(\x0b\x32\x17.logic_to_interface.Pos\x12)\n\x08land_pos\x18\x06 \x01(\x0b\x32\x17.logic_to_interface.Pos\"\x81\x01\n\nPlayerInfo\x12\n\n\x02id\x18\x01 \x01(\x05\x12\n\n\x02HP\x18\x02 \x01(\x05\x12$\n\x03pos\x18\x03 \x01(\x0b\x32\x17.logic_to_interface.Pos\x12\x0e\n\x06weapon\x18\x04 \x01(\x05\x12\r\n\x05\x61rmor\x18\x05 \x01(\x05\x12\x16\n\x0e\x66\x61\x63\x65_direction\x18\x06 \x01(\x01\"F\n\x04Item\x12\n\n\x02id\x18\x01 \x01(\x05\x12\x0c\n\x04type\x18\x02 \x01(\x05\x12$\n\x03pos\x18\x03 \x01(\x0b\x32\x17.logic_to_interface.Pos\"\x8e\x01\n\x06\x42ullet\x12\n\n\x02id\x18\x01 \x01(\x05\x12\x0c\n\x04type\x18\x02 \x01(\x05\x12)\n\x08\x65mit_pos\x18\x03 \x01(\x0b\x32\x17.logic_to_interface.Pos\x12,\n\x0b\x63urrent_pos\x18\x04 \x01(\x0b\x32\x17.logic_to_interface.Pos\x12\x11\n\tdirection\x18\x05 \x01(\x01\"\x92\x01\n\x0bInitialInfo\x12&\n\x05start\x18\x01 \x01(\x0b\x32\x17.logic_to_interface.Pos\x12%\n\x04over\x18\x02 \x01(\x0b\x32\x17.logic_to_interface.Pos\x12\x34\n\x07players\x18\x03 \x03(\x0b\x32#.logic_to_interface.PlayerBasicInfo\"\xe0\x01\n\tFrameInfo\x12\r\n\x05\x66rame\x18\x01 \x01(\x05\x12=\n\x0cparachutists\x18\x02 \x03(\x0b\x32\'.logic_to_interface.PlayerParachuteInfo\x12/\n\x07players\x18\x03 \x03(\x0b\x32\x1e.logic_to_interface.PlayerInfo\x12\'\n\x05items\x18\x04 \x03(\x0b\x32\x18.logic_to_interface.Item\x12+\n\x07\x62ullets\x18\x05 \x03(\x0b\x32\x1a.logic_to_interface.Bulletb\x06proto3')
)




_POS = _descriptor.Descriptor(
  name='Pos',
  full_name='logic_to_interface.Pos',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='x', full_name='logic_to_interface.Pos.x', index=0,
      number=1, type=1, cpp_type=5, label=1,
      has_default_value=False, default_value=float(0),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='y', full_name='logic_to_interface.Pos.y', index=1,
      number=2, type=1, cpp_type=5, label=1,
      has_default_value=False, default_value=float(0),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=39,
  serialized_end=66,
)


_PLAYERBASICINFO = _descriptor.Descriptor(
  name='PlayerBasicInfo',
  full_name='logic_to_interface.PlayerBasicInfo',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='id', full_name='logic_to_interface.PlayerBasicInfo.id', index=0,
      number=1, type=5, cpp_type=1, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='team', full_name='logic_to_interface.PlayerBasicInfo.team', index=1,
      number=2, type=5, cpp_type=1, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='vocation', full_name='logic_to_interface.PlayerBasicInfo.vocation', index=2,
      number=3, type=5, cpp_type=1, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='HP_max', full_name='logic_to_interface.PlayerBasicInfo.HP_max', index=3,
      number=4, type=5, cpp_type=1, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=68,
  serialized_end=145,
)


_PLAYERPARACHUTEINFO = _descriptor.Descriptor(
  name='PlayerParachuteInfo',
  full_name='logic_to_interface.PlayerParachuteInfo',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='id', full_name='logic_to_interface.PlayerParachuteInfo.id', index=0,
      number=1, type=5, cpp_type=1, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='HP', full_name='logic_to_interface.PlayerParachuteInfo.HP', index=1,
      number=2, type=5, cpp_type=1, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='face_direction', full_name='logic_to_interface.PlayerParachuteInfo.face_direction', index=2,
      number=3, type=1, cpp_type=5, label=1,
      has_default_value=False, default_value=float(0),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='pos', full_name='logic_to_interface.PlayerParachuteInfo.pos', index=3,
      number=4, type=11, cpp_type=10, label=1,
      has_default_value=False, default_value=None,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='jump_pos', full_name='logic_to_interface.PlayerParachuteInfo.jump_pos', index=4,
      number=5, type=11, cpp_type=10, label=1,
      has_default_value=False, default_value=None,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='land_pos', full_name='logic_to_interface.PlayerParachuteInfo.land_pos', index=5,
      number=6, type=11, cpp_type=10, label=1,
      has_default_value=False, default_value=None,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=148,
  serialized_end=341,
)


_PLAYERINFO = _descriptor.Descriptor(
  name='PlayerInfo',
  full_name='logic_to_interface.PlayerInfo',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='id', full_name='logic_to_interface.PlayerInfo.id', index=0,
      number=1, type=5, cpp_type=1, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='HP', full_name='logic_to_interface.PlayerInfo.HP', index=1,
      number=2, type=5, cpp_type=1, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='pos', full_name='logic_to_interface.PlayerInfo.pos', index=2,
      number=3, type=11, cpp_type=10, label=1,
      has_default_value=False, default_value=None,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='weapon', full_name='logic_to_interface.PlayerInfo.weapon', index=3,
      number=4, type=5, cpp_type=1, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='armor', full_name='logic_to_interface.PlayerInfo.armor', index=4,
      number=5, type=5, cpp_type=1, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='face_direction', full_name='logic_to_interface.PlayerInfo.face_direction', index=5,
      number=6, type=1, cpp_type=5, label=1,
      has_default_value=False, default_value=float(0),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=344,
  serialized_end=473,
)


_ITEM = _descriptor.Descriptor(
  name='Item',
  full_name='logic_to_interface.Item',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='id', full_name='logic_to_interface.Item.id', index=0,
      number=1, type=5, cpp_type=1, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='type', full_name='logic_to_interface.Item.type', index=1,
      number=2, type=5, cpp_type=1, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='pos', full_name='logic_to_interface.Item.pos', index=2,
      number=3, type=11, cpp_type=10, label=1,
      has_default_value=False, default_value=None,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=475,
  serialized_end=545,
)


_BULLET = _descriptor.Descriptor(
  name='Bullet',
  full_name='logic_to_interface.Bullet',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='id', full_name='logic_to_interface.Bullet.id', index=0,
      number=1, type=5, cpp_type=1, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='type', full_name='logic_to_interface.Bullet.type', index=1,
      number=2, type=5, cpp_type=1, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='emit_pos', full_name='logic_to_interface.Bullet.emit_pos', index=2,
      number=3, type=11, cpp_type=10, label=1,
      has_default_value=False, default_value=None,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='current_pos', full_name='logic_to_interface.Bullet.current_pos', index=3,
      number=4, type=11, cpp_type=10, label=1,
      has_default_value=False, default_value=None,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='direction', full_name='logic_to_interface.Bullet.direction', index=4,
      number=5, type=1, cpp_type=5, label=1,
      has_default_value=False, default_value=float(0),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=548,
  serialized_end=690,
)


_INITIALINFO = _descriptor.Descriptor(
  name='InitialInfo',
  full_name='logic_to_interface.InitialInfo',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='start', full_name='logic_to_interface.InitialInfo.start', index=0,
      number=1, type=11, cpp_type=10, label=1,
      has_default_value=False, default_value=None,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='over', full_name='logic_to_interface.InitialInfo.over', index=1,
      number=2, type=11, cpp_type=10, label=1,
      has_default_value=False, default_value=None,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='players', full_name='logic_to_interface.InitialInfo.players', index=2,
      number=3, type=11, cpp_type=10, label=3,
      has_default_value=False, default_value=[],
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=693,
  serialized_end=839,
)


_FRAMEINFO = _descriptor.Descriptor(
  name='FrameInfo',
  full_name='logic_to_interface.FrameInfo',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='frame', full_name='logic_to_interface.FrameInfo.frame', index=0,
      number=1, type=5, cpp_type=1, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='parachutists', full_name='logic_to_interface.FrameInfo.parachutists', index=1,
      number=2, type=11, cpp_type=10, label=3,
      has_default_value=False, default_value=[],
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='players', full_name='logic_to_interface.FrameInfo.players', index=2,
      number=3, type=11, cpp_type=10, label=3,
      has_default_value=False, default_value=[],
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='items', full_name='logic_to_interface.FrameInfo.items', index=3,
      number=4, type=11, cpp_type=10, label=3,
      has_default_value=False, default_value=[],
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='bullets', full_name='logic_to_interface.FrameInfo.bullets', index=4,
      number=5, type=11, cpp_type=10, label=3,
      has_default_value=False, default_value=[],
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=842,
  serialized_end=1066,
)

_PLAYERPARACHUTEINFO.fields_by_name['pos'].message_type = _POS
_PLAYERPARACHUTEINFO.fields_by_name['jump_pos'].message_type = _POS
_PLAYERPARACHUTEINFO.fields_by_name['land_pos'].message_type = _POS
_PLAYERINFO.fields_by_name['pos'].message_type = _POS
_ITEM.fields_by_name['pos'].message_type = _POS
_BULLET.fields_by_name['emit_pos'].message_type = _POS
_BULLET.fields_by_name['current_pos'].message_type = _POS
_INITIALINFO.fields_by_name['start'].message_type = _POS
_INITIALINFO.fields_by_name['over'].message_type = _POS
_INITIALINFO.fields_by_name['players'].message_type = _PLAYERBASICINFO
_FRAMEINFO.fields_by_name['parachutists'].message_type = _PLAYERPARACHUTEINFO
_FRAMEINFO.fields_by_name['players'].message_type = _PLAYERINFO
_FRAMEINFO.fields_by_name['items'].message_type = _ITEM
_FRAMEINFO.fields_by_name['bullets'].message_type = _BULLET
DESCRIPTOR.message_types_by_name['Pos'] = _POS
DESCRIPTOR.message_types_by_name['PlayerBasicInfo'] = _PLAYERBASICINFO
DESCRIPTOR.message_types_by_name['PlayerParachuteInfo'] = _PLAYERPARACHUTEINFO
DESCRIPTOR.message_types_by_name['PlayerInfo'] = _PLAYERINFO
DESCRIPTOR.message_types_by_name['Item'] = _ITEM
DESCRIPTOR.message_types_by_name['Bullet'] = _BULLET
DESCRIPTOR.message_types_by_name['InitialInfo'] = _INITIALINFO
DESCRIPTOR.message_types_by_name['FrameInfo'] = _FRAMEINFO
_sym_db.RegisterFileDescriptor(DESCRIPTOR)

Pos = _reflection.GeneratedProtocolMessageType('Pos', (_message.Message,), dict(
  DESCRIPTOR = _POS,
  __module__ = 'interface_pb2'
  # @@protoc_insertion_point(class_scope:logic_to_interface.Pos)
  ))
_sym_db.RegisterMessage(Pos)

PlayerBasicInfo = _reflection.GeneratedProtocolMessageType('PlayerBasicInfo', (_message.Message,), dict(
  DESCRIPTOR = _PLAYERBASICINFO,
  __module__ = 'interface_pb2'
  # @@protoc_insertion_point(class_scope:logic_to_interface.PlayerBasicInfo)
  ))
_sym_db.RegisterMessage(PlayerBasicInfo)

PlayerParachuteInfo = _reflection.GeneratedProtocolMessageType('PlayerParachuteInfo', (_message.Message,), dict(
  DESCRIPTOR = _PLAYERPARACHUTEINFO,
  __module__ = 'interface_pb2'
  # @@protoc_insertion_point(class_scope:logic_to_interface.PlayerParachuteInfo)
  ))
_sym_db.RegisterMessage(PlayerParachuteInfo)

PlayerInfo = _reflection.GeneratedProtocolMessageType('PlayerInfo', (_message.Message,), dict(
  DESCRIPTOR = _PLAYERINFO,
  __module__ = 'interface_pb2'
  # @@protoc_insertion_point(class_scope:logic_to_interface.PlayerInfo)
  ))
_sym_db.RegisterMessage(PlayerInfo)

Item = _reflection.GeneratedProtocolMessageType('Item', (_message.Message,), dict(
  DESCRIPTOR = _ITEM,
  __module__ = 'interface_pb2'
  # @@protoc_insertion_point(class_scope:logic_to_interface.Item)
  ))
_sym_db.RegisterMessage(Item)

Bullet = _reflection.GeneratedProtocolMessageType('Bullet', (_message.Message,), dict(
  DESCRIPTOR = _BULLET,
  __module__ = 'interface_pb2'
  # @@protoc_insertion_point(class_scope:logic_to_interface.Bullet)
  ))
_sym_db.RegisterMessage(Bullet)

InitialInfo = _reflection.GeneratedProtocolMessageType('InitialInfo', (_message.Message,), dict(
  DESCRIPTOR = _INITIALINFO,
  __module__ = 'interface_pb2'
  # @@protoc_insertion_point(class_scope:logic_to_interface.InitialInfo)
  ))
_sym_db.RegisterMessage(InitialInfo)

FrameInfo = _reflection.GeneratedProtocolMessageType('FrameInfo', (_message.Message,), dict(
  DESCRIPTOR = _FRAMEINFO,
  __module__ = 'interface_pb2'
  # @@protoc_insertion_point(class_scope:logic_to_interface.FrameInfo)
  ))
_sym_db.RegisterMessage(FrameInfo)


# @@protoc_insertion_point(module_scope)
