# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: logic.proto

import sys
_b=sys.version_info[0]<3 and (lambda x:x) or (lambda x:x.encode('latin1'))
from google.protobuf import descriptor as _descriptor
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor.FileDescriptor(
  name='logic.proto',
  package='comm_logic',
  syntax='proto3',
  serialized_options=None,
  serialized_pb=_b('\n\x0blogic.proto\x12\ncomm_logic\"\x1b\n\x03Pos\x12\t\n\x01x\x18\x01 \x01(\x01\x12\t\n\x01y\x18\x02 \x01(\x01\"?\n\x0fPlayerBasicInfo\x12\n\n\x02id\x18\x01 \x01(\x05\x12\x10\n\x08vocation\x18\x02 \x01(\x05\x12\x0e\n\x06HP_max\x18\x03 \x01(\x05\"\xb2\x01\n\x13PlayerParachuteInfo\x12\n\n\x02id\x18\x01 \x01(\x05\x12\n\n\x02HP\x18\x02 \x01(\x05\x12\x16\n\x0e\x66\x61\x63\x65_direction\x18\x03 \x01(\x01\x12\"\n\tleave_pos\x18\x04 \x01(\x0b\x32\x0f.comm_logic.Pos\x12!\n\x08land_pos\x18\x05 \x01(\x0b\x32\x0f.comm_logic.Pos\x12$\n\x0b\x63urrent_pos\x18\x06 \x01(\x0b\x32\x0f.comm_logic.Pos\"\x91\x01\n\nPlayerInfo\x12\n\n\x02id\x18\x01 \x01(\x05\x12\n\n\x02HP\x18\x02 \x01(\x05\x12\x0e\n\x06weapon\x18\x03 \x01(\x05\x12\r\n\x05\x61rmor\x18\x04 \x01(\x05\x12\x1c\n\x03pos\x18\x05 \x01(\x0b\x32\x0f.comm_logic.Pos\x12\x16\n\x0e\x66\x61\x63\x65_direction\x18\x06 \x01(\x01\x12\x16\n\x0emove_direction\x18\x07 \x01(\x01\">\n\x04Item\x12\n\n\x02id\x18\x01 \x01(\x05\x12\x0c\n\x04type\x18\x02 \x01(\x05\x12\x1c\n\x03pos\x18\x03 \x01(\x0b\x32\x0f.comm_logic.Pos\"~\n\x06\x42ullet\x12\n\n\x02id\x18\x01 \x01(\x05\x12\x0c\n\x04type\x18\x02 \x01(\x05\x12!\n\x08\x65mit_pos\x18\x03 \x01(\x0b\x32\x0f.comm_logic.Pos\x12$\n\x0b\x63urrent_pos\x18\x04 \x01(\x0b\x32\x0f.comm_logic.Pos\x12\x11\n\tdirection\x18\x05 \x01(\x01\"u\n\x0bInitialInfo\x12\x1e\n\x05start\x18\x01 \x01(\x0b\x32\x0f.comm_logic.Pos\x12\x1d\n\x04over\x18\x02 \x01(\x0b\x32\x0f.comm_logic.Pos\x12\'\n\x07players\x18\x03 \x03(\x0b\x32\x16.comm_logic.PlayerInfo\"\xdc\x01\n\x05\x46rame\x12\r\n\x05\x66rame\x18\x01 \x01(\x05\x12\x1e\n\x05plane\x18\x02 \x01(\x0b\x32\x0f.comm_logic.Pos\x12\x35\n\x0cparachutists\x18\x03 \x03(\x0b\x32\x1f.comm_logic.PlayerParachuteInfo\x12\'\n\x07players\x18\x04 \x03(\x0b\x32\x16.comm_logic.PlayerInfo\x12\x1f\n\x05items\x18\x05 \x03(\x0b\x32\x10.comm_logic.Item\x12#\n\x07\x62ullets\x18\x06 \x03(\x0b\x32\x12.comm_logic.Bulletb\x06proto3')
)




_POS = _descriptor.Descriptor(
  name='Pos',
  full_name='comm_logic.Pos',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='x', full_name='comm_logic.Pos.x', index=0,
      number=1, type=1, cpp_type=5, label=1,
      has_default_value=False, default_value=float(0),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='y', full_name='comm_logic.Pos.y', index=1,
      number=2, type=1, cpp_type=5, label=1,
      has_default_value=False, default_value=float(0),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=27,
  serialized_end=54,
)


_PLAYERBASICINFO = _descriptor.Descriptor(
  name='PlayerBasicInfo',
  full_name='comm_logic.PlayerBasicInfo',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='id', full_name='comm_logic.PlayerBasicInfo.id', index=0,
      number=1, type=5, cpp_type=1, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='vocation', full_name='comm_logic.PlayerBasicInfo.vocation', index=1,
      number=2, type=5, cpp_type=1, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='HP_max', full_name='comm_logic.PlayerBasicInfo.HP_max', index=2,
      number=3, type=5, cpp_type=1, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=56,
  serialized_end=119,
)


_PLAYERPARACHUTEINFO = _descriptor.Descriptor(
  name='PlayerParachuteInfo',
  full_name='comm_logic.PlayerParachuteInfo',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='id', full_name='comm_logic.PlayerParachuteInfo.id', index=0,
      number=1, type=5, cpp_type=1, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='HP', full_name='comm_logic.PlayerParachuteInfo.HP', index=1,
      number=2, type=5, cpp_type=1, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='face_direction', full_name='comm_logic.PlayerParachuteInfo.face_direction', index=2,
      number=3, type=1, cpp_type=5, label=1,
      has_default_value=False, default_value=float(0),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='leave_pos', full_name='comm_logic.PlayerParachuteInfo.leave_pos', index=3,
      number=4, type=11, cpp_type=10, label=1,
      has_default_value=False, default_value=None,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='land_pos', full_name='comm_logic.PlayerParachuteInfo.land_pos', index=4,
      number=5, type=11, cpp_type=10, label=1,
      has_default_value=False, default_value=None,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='current_pos', full_name='comm_logic.PlayerParachuteInfo.current_pos', index=5,
      number=6, type=11, cpp_type=10, label=1,
      has_default_value=False, default_value=None,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=122,
  serialized_end=300,
)


_PLAYERINFO = _descriptor.Descriptor(
  name='PlayerInfo',
  full_name='comm_logic.PlayerInfo',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='id', full_name='comm_logic.PlayerInfo.id', index=0,
      number=1, type=5, cpp_type=1, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='HP', full_name='comm_logic.PlayerInfo.HP', index=1,
      number=2, type=5, cpp_type=1, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='weapon', full_name='comm_logic.PlayerInfo.weapon', index=2,
      number=3, type=5, cpp_type=1, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='armor', full_name='comm_logic.PlayerInfo.armor', index=3,
      number=4, type=5, cpp_type=1, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='pos', full_name='comm_logic.PlayerInfo.pos', index=4,
      number=5, type=11, cpp_type=10, label=1,
      has_default_value=False, default_value=None,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='face_direction', full_name='comm_logic.PlayerInfo.face_direction', index=5,
      number=6, type=1, cpp_type=5, label=1,
      has_default_value=False, default_value=float(0),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='move_direction', full_name='comm_logic.PlayerInfo.move_direction', index=6,
      number=7, type=1, cpp_type=5, label=1,
      has_default_value=False, default_value=float(0),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=303,
  serialized_end=448,
)


_ITEM = _descriptor.Descriptor(
  name='Item',
  full_name='comm_logic.Item',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='id', full_name='comm_logic.Item.id', index=0,
      number=1, type=5, cpp_type=1, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='type', full_name='comm_logic.Item.type', index=1,
      number=2, type=5, cpp_type=1, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='pos', full_name='comm_logic.Item.pos', index=2,
      number=3, type=11, cpp_type=10, label=1,
      has_default_value=False, default_value=None,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=450,
  serialized_end=512,
)


_BULLET = _descriptor.Descriptor(
  name='Bullet',
  full_name='comm_logic.Bullet',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='id', full_name='comm_logic.Bullet.id', index=0,
      number=1, type=5, cpp_type=1, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='type', full_name='comm_logic.Bullet.type', index=1,
      number=2, type=5, cpp_type=1, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='emit_pos', full_name='comm_logic.Bullet.emit_pos', index=2,
      number=3, type=11, cpp_type=10, label=1,
      has_default_value=False, default_value=None,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='current_pos', full_name='comm_logic.Bullet.current_pos', index=3,
      number=4, type=11, cpp_type=10, label=1,
      has_default_value=False, default_value=None,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='direction', full_name='comm_logic.Bullet.direction', index=4,
      number=5, type=1, cpp_type=5, label=1,
      has_default_value=False, default_value=float(0),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=514,
  serialized_end=640,
)


_INITIALINFO = _descriptor.Descriptor(
  name='InitialInfo',
  full_name='comm_logic.InitialInfo',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='start', full_name='comm_logic.InitialInfo.start', index=0,
      number=1, type=11, cpp_type=10, label=1,
      has_default_value=False, default_value=None,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='over', full_name='comm_logic.InitialInfo.over', index=1,
      number=2, type=11, cpp_type=10, label=1,
      has_default_value=False, default_value=None,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='players', full_name='comm_logic.InitialInfo.players', index=2,
      number=3, type=11, cpp_type=10, label=3,
      has_default_value=False, default_value=[],
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=642,
  serialized_end=759,
)


_FRAME = _descriptor.Descriptor(
  name='Frame',
  full_name='comm_logic.Frame',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='frame', full_name='comm_logic.Frame.frame', index=0,
      number=1, type=5, cpp_type=1, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='plane', full_name='comm_logic.Frame.plane', index=1,
      number=2, type=11, cpp_type=10, label=1,
      has_default_value=False, default_value=None,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='parachutists', full_name='comm_logic.Frame.parachutists', index=2,
      number=3, type=11, cpp_type=10, label=3,
      has_default_value=False, default_value=[],
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='players', full_name='comm_logic.Frame.players', index=3,
      number=4, type=11, cpp_type=10, label=3,
      has_default_value=False, default_value=[],
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='items', full_name='comm_logic.Frame.items', index=4,
      number=5, type=11, cpp_type=10, label=3,
      has_default_value=False, default_value=[],
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='bullets', full_name='comm_logic.Frame.bullets', index=5,
      number=6, type=11, cpp_type=10, label=3,
      has_default_value=False, default_value=[],
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=762,
  serialized_end=982,
)

_PLAYERPARACHUTEINFO.fields_by_name['leave_pos'].message_type = _POS
_PLAYERPARACHUTEINFO.fields_by_name['land_pos'].message_type = _POS
_PLAYERPARACHUTEINFO.fields_by_name['current_pos'].message_type = _POS
_PLAYERINFO.fields_by_name['pos'].message_type = _POS
_ITEM.fields_by_name['pos'].message_type = _POS
_BULLET.fields_by_name['emit_pos'].message_type = _POS
_BULLET.fields_by_name['current_pos'].message_type = _POS
_INITIALINFO.fields_by_name['start'].message_type = _POS
_INITIALINFO.fields_by_name['over'].message_type = _POS
_INITIALINFO.fields_by_name['players'].message_type = _PLAYERINFO
_FRAME.fields_by_name['plane'].message_type = _POS
_FRAME.fields_by_name['parachutists'].message_type = _PLAYERPARACHUTEINFO
_FRAME.fields_by_name['players'].message_type = _PLAYERINFO
_FRAME.fields_by_name['items'].message_type = _ITEM
_FRAME.fields_by_name['bullets'].message_type = _BULLET
DESCRIPTOR.message_types_by_name['Pos'] = _POS
DESCRIPTOR.message_types_by_name['PlayerBasicInfo'] = _PLAYERBASICINFO
DESCRIPTOR.message_types_by_name['PlayerParachuteInfo'] = _PLAYERPARACHUTEINFO
DESCRIPTOR.message_types_by_name['PlayerInfo'] = _PLAYERINFO
DESCRIPTOR.message_types_by_name['Item'] = _ITEM
DESCRIPTOR.message_types_by_name['Bullet'] = _BULLET
DESCRIPTOR.message_types_by_name['InitialInfo'] = _INITIALINFO
DESCRIPTOR.message_types_by_name['Frame'] = _FRAME
_sym_db.RegisterFileDescriptor(DESCRIPTOR)

Pos = _reflection.GeneratedProtocolMessageType('Pos', (_message.Message,), dict(
  DESCRIPTOR = _POS,
  __module__ = 'logic_pb2'
  # @@protoc_insertion_point(class_scope:comm_logic.Pos)
  ))
_sym_db.RegisterMessage(Pos)

PlayerBasicInfo = _reflection.GeneratedProtocolMessageType('PlayerBasicInfo', (_message.Message,), dict(
  DESCRIPTOR = _PLAYERBASICINFO,
  __module__ = 'logic_pb2'
  # @@protoc_insertion_point(class_scope:comm_logic.PlayerBasicInfo)
  ))
_sym_db.RegisterMessage(PlayerBasicInfo)

PlayerParachuteInfo = _reflection.GeneratedProtocolMessageType('PlayerParachuteInfo', (_message.Message,), dict(
  DESCRIPTOR = _PLAYERPARACHUTEINFO,
  __module__ = 'logic_pb2'
  # @@protoc_insertion_point(class_scope:comm_logic.PlayerParachuteInfo)
  ))
_sym_db.RegisterMessage(PlayerParachuteInfo)

PlayerInfo = _reflection.GeneratedProtocolMessageType('PlayerInfo', (_message.Message,), dict(
  DESCRIPTOR = _PLAYERINFO,
  __module__ = 'logic_pb2'
  # @@protoc_insertion_point(class_scope:comm_logic.PlayerInfo)
  ))
_sym_db.RegisterMessage(PlayerInfo)

Item = _reflection.GeneratedProtocolMessageType('Item', (_message.Message,), dict(
  DESCRIPTOR = _ITEM,
  __module__ = 'logic_pb2'
  # @@protoc_insertion_point(class_scope:comm_logic.Item)
  ))
_sym_db.RegisterMessage(Item)

Bullet = _reflection.GeneratedProtocolMessageType('Bullet', (_message.Message,), dict(
  DESCRIPTOR = _BULLET,
  __module__ = 'logic_pb2'
  # @@protoc_insertion_point(class_scope:comm_logic.Bullet)
  ))
_sym_db.RegisterMessage(Bullet)

InitialInfo = _reflection.GeneratedProtocolMessageType('InitialInfo', (_message.Message,), dict(
  DESCRIPTOR = _INITIALINFO,
  __module__ = 'logic_pb2'
  # @@protoc_insertion_point(class_scope:comm_logic.InitialInfo)
  ))
_sym_db.RegisterMessage(InitialInfo)

Frame = _reflection.GeneratedProtocolMessageType('Frame', (_message.Message,), dict(
  DESCRIPTOR = _FRAME,
  __module__ = 'logic_pb2'
  # @@protoc_insertion_point(class_scope:comm_logic.Frame)
  ))
_sym_db.RegisterMessage(Frame)


# @@protoc_insertion_point(module_scope)
